Cloud-Pipelines/pipeline-studio-app

.gitignore
src/index.tsx

This PR adds environment variables responsible for toggling `scan` and `router dev tools`. In VITE you have to prefix your variables with VITE_
```
VITE_ENABLE_SCAN=true
VITE_ENABLE_ROUTER_DEVTOOLS=false
```

Adds scan and router dev tools though env file

---

package-lock.json
package.json
src/DragNDrop/ArgumentsEditorDialog.tsx
src/DragNDrop/ComponentTaskNode.tsx
src/index.tsx

closes: https://github.com/Shopify/oasis-project/issues/5 https://github.com/Shopify/oasis-project/issues/4
Currently, the dialog box for arguments has two bugs:
1: Moving the box moves the node
2: double clicking the box closes it
This PR aims to address those two issues by using MUI dialog and `react-draggable`.
- I've moved the dialog outside of the  `src/DragNDrop/ComponentTaskNode.tsx`  main `div` that had the double click handler on it. Instead this component now has two components; the main `div` with the click handler and the dialog, which are both wrapped in a react fragment <></>. This allows us to double click anywhere on the argument box.
- The dialog box itself uses portals, allowing us to drag anywhere we want
- I've also cleaned up some of the styles that were previously …

fix: Argument Editor - Fixed Dialog double click and movement issues

---

src/appSettings.ts

Create React App (CRA): When using process.env.PUBLIC_URL in Create React App, it typically does not include a trailing slash. You often need to manually add a trailing slash if you're constructing paths based on it. For instance, you might end up doing something like ${process.env.PUBLIC_URL}/path instead of assuming the slash is already present.
Vite with Tanstack (or other modern tools): In Vite, import.meta.env.BASE_URL generally includes a trailing slash at the end. This means if you're constructing paths, you don't need to add another slash manually; you can simply use it like ${import.meta.env.BASE_URL}path.

Updates path for component library and pipeline library

---

src/routes/RunDetails.tsx
src/utils/copyRunToPipeline.ts

This PR adds a util function that will take a componentSpec, removes any status, then saves it to indexDB with a new name (if required) and returns the new name and url to that new pipeline. I've also added a button to the control component on the  run graph to use this functionality. 
If the name exists it will append (copy) or (copy N) to the end of it.
I've also made the control component slightly larger on this view only. 
I've also made the graph fit to view and made the nodes non-draggable.

Adds clone button to graph controls

---

src/routes/Home.tsx

Fixes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/76
For every `fetch` call, we need to check the HTTP response code.

fix: Fixed the "Something went wrong" - Cannot read properties of undefined (reading 'map')

---

src/components/AppMenu.tsx
src/components/CloneRunButton.tsx
src/hooks/useLoadComponentSpecDetailsFromId.ts
src/routes/Home.tsx
src/routes/RunDetails.tsx
src/utils/constants.ts

This PR moves the clone button from the graph controls to the header. This has been achieved by creating a clone run button component that works by accepting an ID as a param. We can place this anywhere we have access to the ID now.

Move the clone button from graph to header

---

src/components/AppMenu.tsx
src/components/PipelineRow/index.tsx

Closes: https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/87
You can now right click the app logo to open a link context menu or command click to open in a new window. You can also command click anywhere on the row for a pipeline to open it in a new window or you can right click the title to open in a new window from the context menu

feat: Run list - Run names are now links that can be opened in new tab

---

src/DragNDrop/ArgumentsEditorDialog.tsx

This PR adds a "Grip" icon to indicate to the user they can grab there and move the arguments box. I've also added a cursor icon of "move" when they hover.

visual: Argument editor - Added a grip icon next to argument modal title to indicate that the dialog is draggable

---

src/DragNDrop/ShopifyCloud.tsx

When a user submits a pipeline and it fails, we now display a message:
closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/80

feat: Run submitter - Added submission error indication

---

src/DragNDrop/AppSettingsDialog.tsx
src/DragNDrop/PipelineLibrary.tsx
src/DragNDrop/UserComponentLibrary.tsx

This PR addresses three items:
1. Fixes a couple instances of broken "x" (close) buttons on Dialog components.
2. Addresses instances of a Radix warning about missing Dialog aria-description by adding a hidden description field.
3. Addresses instances of a Radix error about missing Dialog aria-title by removing manual `aria-labelledby` assignments (Radix takes care of this internally)
No more Radix-Dialog errors or warnings in the console:

chore: Dialogs - Added missing dialog titles, descriptions and onOpenChange handlers

---

src/DragNDrop/PipelineLibrary.tsx
src/componentStore.ts

Closes https://github.com/Shopify/oasis-frontend/issues/8
Fixes an issue where the 'save' button was acting as a 'save as' action and prompting input and confirmation.
Also fixes a fetch error that occurs once saving has been completed.

Fix for 'save' button prompting an overwrite

---

src/DragNDrop/GraphComponentSpecFlow.tsx
src/utils/updateNodePosition.ts

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/98
Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/99
Fixes an issue where a selected group of tasks could not be moved or deleted as a group.
This was occurring due to the move & delete operations not updating the graph spec in real-time, and instead overwriting the updated graph spec with the original when a new task is operated upon. This resulted in only the final task being moved or deleted. In the case of the delete function this was a by-product of React's state update logic, which meant that the delete operations were running on old state as the component doesn't rerender until the current operations have finished.
The operations will now run on a graph spec that is updated after each …

Fix broken group Drag-n-Drop & Delete

---

src/components/ui/spinner.tsx
src/routes/Home.tsx

Related to https://github.com/Shopify/oasis-frontend/issues/6
Shifts around some of the frontend logic on the Home Page so that parts of the page that have loaded can be displayed while slower requests are still being completed. Does not address the core problem in the linked Issue, but does mitigate its impact.
Also adds a loading Spinner and an Empty State for Pipelines and Runs.

Improvements to Home Page loading state UX

---

src/components/PipelineRow/RunListItem.tsx
src/components/PipelineRow/StatusIcon.tsx
src/components/PipelineRow/TaskStatusBar.tsx
src/components/PipelineRow/index.tsx
src/components/PipelineRow/types.ts
src/components/PipelineRow/utils.ts
src/routes/Home.tsx
src/utils/fetchPipelineRuns.ts

Addresses items on https://github.com/Shopify/oasis-frontend/issues/9 and https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/105
- Condenses the "latest run" on the Pipeline Row into one cell, adds the run creation date and hides the hardcoded placeholder run duration.
- Displays the run creation date on the run list
- Replaces the loading spinner with a warning triangle on runs with no status
- A little bit of refactoring/reorganization to facilitate the above two items. (mostly moving shared methods and run status calculation to a new, shared, method)

Improve display of run data on PipelineRow and RunList

---

eslint.config.js
src/components/PipelineRow/RunListItem.tsx
src/components/PipelineRow/StatusText.tsx
src/components/PipelineRow/index.tsx
src/components/PipelineSection/PipelineSection.tsx
src/components/PipelineSection/index.ts
src/components/RunSection/RunRow.tsx
src/components/RunSection/RunSection.tsx
src/components/RunSection/index.ts
src/routes/Home.tsx
src/utils/fetchPipelineRuns.ts

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/105
Converts the Run list into a Table, and adds `created_by` info, if available.
This requires a bit of reorganization and refactoring of the Home page (+ separation of concerns).
- Pipeline Tab React code moved into its own PipelineSection, including supporting methods.
- Refresh button was only being used for Pipelines, so this is no longer available in the Run Tab.
- Run Tab React code moved into its own RunSection, including supporting methods.
- Run Tab now display information in a Table.
- Run Status bar is no longer the width of the entire screen.
- Shorthand variant added to Run StatusText, creating a more condensed string. This is now used in RunList which is now exclusively used in the Pipeline Section run …

Convert Run List into Table

---

src/DragNDrop/ArgumentsEditor.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/17
This PR makes argument editors scrollable, the labels break, the labels remove `_`, and the types get truncated if they are too long and have a hover

Fix Large list of options is too long, and not scrollable

---

src/components/PipelineSection/PipelineSection.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/22
The pipeline section was removing "_" from pipeline names, causing links to not render out correctly. 
Fixes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/158

Removes replacing _ from pipeline name

---

src/components/CloneRunButton.tsx
src/components/NewExperiment.tsx
src/components/shared/PipelineNameDialog.tsx
src/hooks/useLoadUserPipelines.tsx
src/utils/constants.ts
src/utils/copyRunToPipeline.ts

When a user clones a run, we now prompt them to either accept the original name + date time (to keep unique) or add their own unique name.
New pipeline and clone run share some logic, so I've moved that logic into a hook

We now prompt the user to rename their cloned pipeline

---

src/DragNDrop/PipelineSubmitter.tsx
src/DragNDrop/ShopifyCloud.tsx
src/componentSpec.ts
src/components/ArgumentsEditor/ArgumentInputField.tsx
src/components/ArgumentsEditor/ArgumentsEditor.tsx
src/components/ArgumentsEditor/ArgumentsEditorDialog.tsx

Follow-up to https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/163
- Argument Input Fields will be pre-populated with their default value if there is one.
- Argument Input Fields will be "Included" if there is a default value.
- "Excluded" Argument Input Fields can be typed in to. Typing will automatically "Include" the field.
- Empty fields will now show their default value as a placeholder, if there is one.
- Simplified placeholder logic - removed the `linkedNodes` property from `ArgumentInput` as I found a smarter way of managing placeholder text.
- Moved the `ArgumentInput` type into the `ArgumentEditorInput` component.

Improve logic for Argument Editor placeholders and defaults

---

package-lock.json
package.json
src/components/PipelineRow/RunListItem.tsx
src/components/PipelineRow/StatusText.tsx
src/components/PipelineRow/index.tsx
src/components/RunSection/RunRow.tsx
src/components/ui/hover-card.tsx

closes https://github.com/Shopify/oasis-frontend/issues/21
- Status information was overcrowded when displaying multiple states (successful, running, errors, skipped)
- Pipeline run list items became cluttered after switching to UUID format
- Status count information took up unnecessary space in the main view
- Implemented a card popover that appears when hovering over the status bar
- Moved detailed status counts to the hover popover
- Retained the progress bar as the primary visual indicator
- Simplified the main UI while keeping detailed information easily accessible
- Status counts are now available on-demand via hover interaction
- Progress bar continues to provide visual feedback of overall pipeline status
- Improved space efficiency in pipeline run list items
- Better handling of …

Fix status count crowding on run row

---

src/DragNDrop/ComponentTaskNode.tsx
src/DragNDrop/DraggableComponent.tsx
src/DragNDrop/DraggableDialog.tsx
src/DragNDrop/GraphComponentSpecFlow.tsx
src/DragNDrop/ShopifyCloud.tsx
src/DragNDrop/UserComponentLibrary.tsx
src/components/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/custom/ConfirmationDialog.tsx
src/components/ui/button.tsx
src/hooks/useComponentSpecToNodes.test.tsx
src/hooks/useComponentSpecToNodes.tsx

Addresses some of the items in https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/131
- Moves the UserComponent Delete Button to a small X in the top right.
- Adds a delete button for the component on the argument editor
- Moves the close button in the argument editor to a small X in the top right
- Changes the 'clear argument' button in the argument editor to a delete icon.
- Adds a Confirmation Dialog before anything on the graph is deleted

Improved UX for deleting components

---

src/DragNDrop/GraphComponentSpecFlow.tsx

During Hoda's review/demo she had trouble deleting a component. This was due to confusion over whether to use `delete` or `backspace`. Now, either option is acceptable.
The Apple-check has also been removed as it appears to be unnecessary.
Also fixes a bug where trying to delete with nothing selected would crash the app.

Delete and Backspace now both remove components

---

.vscode/settings.json
src/App.tsx
src/DragNDrop/DraggableComponent.tsx
src/DragNDrop/GraphComponentLink.tsx
src/DragNDrop/UserComponentLibrary.tsx
src/components/PipelineSection/PipelineSection.tsx
src/components/RunSection/RunRow.tsx
src/components/TaskDetailsSheet/artifacts.tsx
src/components/shared/PipelineNameDialog.tsx

No more use of `React.[module]`, except in the `ui` folder.
(I tried to put together an ESLint rule to enforce this but couldn't quite get it working... maybe in the future I'll try again)

Explicit import from React

---

src/components/shared/Dialogs/ConfirmationDialog.tsx
src/components/shared/Dialogs/DraggableDialog.tsx
src/components/shared/ReactFlow/FlowGraph/FlowGraph.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskNode.tsx
src/utils/nodes/createNodes.test.ts
src/utils/nodes/createNodes.ts

Some changes to the Arguments Editor:
1. Remove the 'Setting' button - a single click (not drag) will now open the Argument Editor
2. `esc` to close the editor (applies to all other dialogs as well) - nb. click-outside the editor will not close it so that users can still click and drag around the graph without closing the editor
3. Fix `delete` node button not working
4. Delete Confirmation Dialog will not longer appear behind other dialogs
5. Argument Editor Dialog will remain open while the user confirms deletion (i.e. if the delete operation is canceled the dialog doesn't need to be reopened)
6. Fix app crash when applying changes to arguments
Closes https://github.com/Shopify/oasis-frontend/issues/39
Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/183
This PR will …

Argument Editor Improvements

---

src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskDetailsSheet/index.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskNode.tsx

resolves: https://github.com/Shopify/oasis-frontend/issues/62
Similar to the pipeline editor, I have removed all icons from the node and now we can just click the node to show the sheet. I have also made it so if you click outside of the sheet it will close. 
I have also updated the status indicators. Instead of an Icon telling us what the status is, we only show the status colour on the nodes. additionally I have made the running nodes pulse slightly to signify that it is running
note: this video shows random status I forced through code.
https://github.com/user-attachments/assets/01e5e292-a1cb-4e67-a18f-78069dce599c

Removes info icon so you can click the node anywhere to see details

---

src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/UserComponentItem.tsx

The user components now have a delete button no matter the length of the title
Components now have a link button no matter the length of their name
Closes https://github.com/Shopify/oasis-frontend/issues/65

Fixes delete user components bug and adds component link

---

src/components/shared/ReactFlow/FlowGraph/FlowGraph.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowGraph/utils/cleanupDeletedTasks.ts
src/utils/nodes/createNodes.ts

Selection state is now synced with componentSpec, allowing selection state to be persisted across operations (such as moving nodes on the canvas).
- Selected Nodes now stored in state for future reference
- Selected Nodes remain selected after moving or operating on them
- Selection border takes precedence over hover border
Also fixes the regression introduced in #199 that removed the dynamic delete dialog text.
Natively ReactFlow already persists selection state across operations. However, in Oasis, we are rebuilding the entire node graph from scratch (based on the componentSpec) every time an operation is completed, meaning the selection state currently gets reset frequently.
To solve this a much larger refactor will be needed in future: …

Sync FlowGraph selection state with componentSpec

---

src/components/shared/ReactFlow/FlowGraph/FlowGraph.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskNode.tsx
src/types/taskNode.ts
src/utils/nodes/createNodes.test.ts
src/utils/nodes/duplicateNode.ts

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/156
Closes https://github.com/Shopify/oasis-frontend/issues/24
Adds a button to the Arguments Editor that will duplicate a node, including any input connections it has.
The original node will be deselected and the arguments editor closed.
Follows #204 
Progresses toward https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/169
Note: The arguments editor is not the ideal place for a duplicate button, but we currently do not have a better place to put this action so this is where it will live for now.

Duplicate Node

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/utils/nodes/createNodes.ts

A high-level change to shift the manual node operations on reactflow from `replace` to `update`. In other words, this PR makes it so that we no longer fully replace the node array upon each change to component spec. Instead, existing nodes will be updated, allowing Node state (such as selection) to be preserved between renders.
Related: https://github.com/Shopify/oasis-frontend/issues/61
Further granularity and optimization will be needed before https://github.com/Shopify/oasis-frontend/issues/61 can be considered fully addressed (ideally, we should only update nodes that have changed, or bundle updates together and apply at once). But this is a good first step.
This PR is needed to solve some issues in https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/169 where the toolbar …

Update nodes on render instead of replace

---

src/components/Editor/PipelineEditor.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/styles/editor.css

Minimap moved to the left so it no longer gets cover by sidebar sheets that may appear on the right on the screen.
Also makes the minimap pannable and removes the `ReactFlow` label.

Move minimap to the left

---

src/components/shared/Dialogs/ConfirmationDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/removeEdge.ts
src/components/shared/ReactFlow/FlowCanvas/utils/setTaskArgument.ts

Fixes a bug where Edges cannot be manually delete from the canvas.
Also adds Edge-specific text to the confirmation dialog. And allows the dialog to accept ReactNode content.
This PR also appears to fix the underlying issue that #197 was created to address.

Fix inability to delete Edges

---

src/components/deprecated/Sidebar/PipelineSubmitter/PipelineSubmitter.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentInputField.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsSection.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/index.ts
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/ui/sheet.tsx
src/styles/global.css
src/types/arguments.ts
src/utils/constants.ts

Closes https://github.com/Shopify/oasis-frontend/issues/50
Migrates the Arguments Editor into a pop-up side-sheet.
Also adds a button to copy component yaml to clipboard.
**Known issues**
- Not strictly a regression, but it is now more difficult to copy arguments between nodes, since only one editor can now be open at a time. This will be addressed separately at some point in the future.
- There is a bug where unsetting an argument resets it to default when reopening the editor. This will be addressed as part of https://github.com/Shopify/oasis-frontend/issues/83, since that will rework a lot of the argument input logic anyway.
- There are a few other tidbits (particularly UX) relating to editing arguments which will be address as part of …

Move Argument Editor to Side-Sheet

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskDetailsSheet/index.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/utils/nodes/createNodesFromComponentSpec.test.ts
src/utils/nodes/createNodesFromComponentSpec.ts
src/utils/nodes/createTaskNode.ts

Follows #213 
Fixes:
- Wonky sheet position due to Tailwind unable to parse computed value
- Config Sheet overruling Details sheet when viewing Nodes info in a Run
- TaskNode now has access to the ReactFlow `readOnly` state via `data.readOnly` (useful to distinguish between Pipeline Editor and Run views).
- Minor alignments between Config and Details sheets

Fix errors in Sheet logic

---

src/components/shared/CondensedUrl.tsx
src/components/ui/link.tsx

Adds a customized `a` tag that allows us to render an external link indicator next to a url

Add Link component

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskDetailsSheet/logs.tsx

closes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/168
This PR should fix issues where logs don't exist and error happens as well as displays the `system_error_exception_full` if they do exist.

Adds system error logs

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/hooks/useCopyPaste.ts
src/types/taskNode.ts
src/utils/nodes/copyToNewTaskNode.ts

Progresses https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/19
Implements Copy + Pasting of Task Nodes via `ctrl-c + ctrl-v` (or cmd on mac).
- New `useCopyPaste` hook to manage copy + paste callbacks
- Copy will save the selected nodes to the clipboard as a JSON string
- Paste will attempt to parse the saved string in the clipboard into a Node object and then place it in the centre of the current ReactFlow instance.
- Arguments and other task data will be copied over, but edges/connections to other nodes will be removed.
- Assuming correct structure nodes can be pasted into any pipeline editor instance even if it did not originate from that instance.
- The new node(s) will be selected and everything else deselected. …

Copy + Paste Singular Nodes

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskDetailsSheet/logs.tsx
src/hooks/useCopyPaste.ts

Bugfix ReactFlow copy+paste for nodes overriding argument input.
`useCopyPaste` will no longer fire callbacks if copy+paste is used within an input field or textarea.
Note: seems like a `npm validate` was missed in a previous PR so most of this PR is just formatting

useCopyPaste hook no longer overrides TextBoxes

---

src/components/deprecated/Sidebar/GraphComponentExporter.tsx
src/components/deprecated/Sidebar/PipelineLibrary/GraphComponentLink.tsx
src/components/deprecated/Sidebar/VertexAiExporter.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx
src/utils/nodes/updateComponentSpecFromNodes.ts
src/utils/storage.ts

Closes https://github.com/Shopify/oasis-frontend/issues/67
Also, for safety I've filtered out the selection toolbar node from the nodes array before it gets passed into the relevant hook.

Fix Race Condition in Pipeline Export

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/hooks/useSelectionToolbar.ts

Toolbar no longer renders in run view.
And a note on why we are using `data.hidden` rather than ReactFlow's native `hidden` property.

Quick Toolbar Update

---

src/components/shared/ReactFlow/FlowSidebar/components/FolderItem.tsx

Superquick fix to this error that appears when exploring the componentsidebar:

Fix Missing Key in Component Sidebar

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Fixes and issue where the hidden `selection-toolbar` is impacting the viewport on load. The viewport will now load centred on the task nodes again.

Fix Toolbar Impacting Viewport Bounds on Load

---

src/components/shared/CodeViewer.tsx
src/components/shared/Dialogs/ComponentDetails/tabs/index.ts
src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/Dialogs/index.ts
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/UserComponentItem.tsx
src/components/shared/TaskDetails/Details.tsx
src/components/shared/TaskDetails/IO.tsx
src/components/shared/TaskDetails/Implementation.tsx
src/components/shared/TaskDetails/index.ts
src/utils/getComponentFilename.ts
src/utils/getComponentName.ts

Closes https://github.com/Shopify/oasis-frontend/issues/79
Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/23
Adds tabs to the TaskConfig sheet for Task Nodes in the pipeline editor.
Tabs are:
- Details: uses the same component as the TaskInfo sheet
- Arguments: uses the existing arguments components
- Implementation: uses the same component as thew TaskInfo sheet
Removes the component url from the header as it is now surfaced in the `details` tab.
Also includes a few misc improvements, such as the yaml filename on the implementation tab codeviewer

Add Details and Implementation Tabs to Task Config Sheet

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/providers/ComponentSpecProvider.tsx
src/routes/PipelineRun/PipelineRun.tsx

I've added to the componentspec provider to also hold the status of the nodes. We need to do this because the API can't block or re-render the entire tree on every call. This fixes the issue where we were not seeing the status updating.
https://github.com/user-attachments/assets/906a7c84-7bcd-43ea-a58d-992cbbccaa6d

Removes blanks state for missing state

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/duplicateNodes.ts
src/types/taskNode.ts
src/utils/nodes/copyToNewTaskNode.ts
src/utils/nodes/createNodesFromComponentSpec.test.ts
src/utils/nodes/createNodesFromComponentSpec.ts
src/utils/nodes/createTaskNode.ts
src/utils/nodes/duplicateTask.ts
src/utils/nodes/generateDynamicNodeCallbacks.ts

Some rework of TaskNode stuff relating to duplication. 
- Create new nodes directly inside the duplicate nodes method
- move some types to more logical places
- where possible, node data is copied over from original nodes when duplicated
- Singular node duplication now uses the same method as bulk duplication
- fix for pasting nodes into run view
- fix a typo in the node delete dialog
No changes to app functionality (except bugfixes)

Update duplicate nodes method

---

src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/TaskDetails/Details.tsx
src/utils/URL.ts
src/utils/string.ts
src/utils/yaml.ts

I have updated the sheet and dialog for task/nodes:
- Copy now copies the entire YAML not the just the implementation portion
- Actions
- I have moved the actions to the action portion of the src/components/shared/TaskDetails/Details.tsx for consistency
- I moved some logic, like copy YAML and download to the details component
- I've removed the text next to the buttons, and gave them new icons that I believe better represent the action.
- I've added tool tips to the buttons
- I've added a collapsible component around description as the information isn't immediately  required and causes the details to grow quite large in some cases 
- I've moved the task ID to the details component instead of under the header
https://github.com/user-attachments/assets/e5951eaa-9314-434b-b1c8-acda799cb5ce

Update the task/node info sheet/dialog

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/hooks/useConfirmationDialog.ts

useConfirmationDialog hook can now track and set dialog title, description and content when the dialog is triggered.

ConfirmationDialog hook accepts metadata when triggered

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentInputField.tsx

Minor change to add a tooltip to the placeholder on Argument Input so the full value can be read

Add Tooltip to Argument Input Placeholders

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/TaskDetails/Details.tsx
src/components/ui/sidebar.tsx

The `Tooltip` component has its own provider built in, so we don't need to manually call it each time we want to use a tooltip.

Remove unnecessary instances of TooltipProvider

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Closes https://github.com/Shopify/oasis-frontend/issues/88
But is not a perfect solution.
Basically works by creating new nodes when dropped & before the actual node creation happens, so that when the callbacks are added to the node they can already reference the node that has just been made.

Workaround for Node Callbacks not working on first render

---

src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/DeleteConfirmation.tsx
src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/ReplaceConfirmation.tsx
src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/shared.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowCanvas/types.ts
src/components/shared/ReactFlow/FlowCanvas/utils/isPositionInNode.ts
src/components/shared/ReactFlow/FlowCanvas/utils/replaceTaskNode.ts
src/hooks/useConfirmationDialog.ts
src/types/taskNode.ts
src/utils/deepClone.ts
src/utils/nodes/createTaskNode.ts

Closes https://github.com/Shopify/oasis-frontend/issues/74
Replace task nodes on the canvas by dragging a Task from the sidebar on top of them. The node will highlight orange if the drop operation will trigger a replacement and a confirmation dialog will appear when the drop occurs.
Upon confirmation the new task node will replace the old one, assuming its position and attempting to maintain as many arguments, inputs and outputs as possible.
https://github.com/user-attachments/assets/26219321-7dca-4cd3-90f7-6f0b6ed0b93c
Replacement by Input/Output node is currently unsupported, due to these nodes not being available in the sidebar. We will need to make them compatible once they are available.
Upgrade-in-Place and Group-Replace features will come in later PRs.

Drag and Drop to Replace Nodes

---

src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/ReplaceConfirmation.tsx
src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/shared.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/replaceTaskNode.ts
src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/hooks/useComponentFromUrl.ts

Precursor to #253 
Just moving some things around, breaking things into their own files or functions so that code can be more easily reached and read. This will keep the size of #253 a little more focused and manageable.
Notably: adds a useComponentFromUrl hook that encapsulates the component fetching logic in the sidebar (this will be used in #253). Also condenses our ReactFlow confirmation dialogs into one.
No change to app functionality.

Reorganize and Refactor some recent node replacement logic

---

src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/BulkUpdateConfirmationDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/SelectionToolbar.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/replaceTaskNode.ts

Continues on from #253 and #242 to allow nodes to be upgrade in bulk by selecting a group of them on the canvas and choosing the new bulk-upgrade button on the selection toolbar.
A continuation of https://github.com/Shopify/oasis-frontend/issues/74
The system will warn if some inputs may be lost, but will not list what those inputs or arguments are. Replacement logic is the same as #242.

Bulk Upgrade Nodes via Selection Toolbar

---

src/hooks/useCopyPaste.ts

A little more reliable logic for ctrl-c & ctrl-v triggering a callback vs copying text.
New logic:
If the event target is editable, or if the window has a selected element and that element has text content, do not trigger the callback (copy the text content instead).

More comprehensive copy+paste fix

---

package-lock.json
package.json
src/components/shared/TaskDetails/Details.tsx

if `original_python_code` exists in the metadata we will display a download button

If original_python_code show download button

---

src/components/shared/CodeViewer.tsx
src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/OasisSubmitter.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/logs.tsx
src/components/shared/TaskDetails/Implementation.tsx

Previously, you had to click the code once it was in full screen mode to make it scrollable. this resolves that by closing the side pane allowing the browser to scroll the full screen code. I have also updated the name of the arguments depending on if its a run or a pipeline.

This PR fixes the full screen code viewer so it immediately becomes scrollable

---

src/components/Home/PipelineSection/PipelineRow/PipelineRow.tsx
src/components/Home/RunSection/RunRow.tsx
src/utils/date.ts

This PR adds a new date method that takes a UTC date and converts it to the local timezone. This is currently being used on the pipeline runs table as well as the "last run" column on the pipeline table.

Adds local dates on the pipeline and runs list

---

src/components/Home/RunSection/RunSection.tsx
src/services/executionService.ts

When we tab back to the home page we re-fetch our data. We don't want this because it can lead to some ugly UI. This resolves that.

Don't fetch runs when home page is refocused

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/ioCell.tsx
src/components/ui/link.tsx

The links in the artifacts ioCell now link externally. Because the text is so small I had to update the link component so you can adjust the icon class names from the parent.

Makes artifacts link open in new tab

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/utils/string.ts

This PR shows the value and default value on the task node. If we show the default value, its slightly lighter to signal to our users this is a default value.
Name is too long
Value is too long
Both are too long

Add the values directly on the task node

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/replaceTaskAnnotationsInGraphSpec.ts
src/types/annotations.ts
src/types/taskNode.ts
src/utils/nodes/createNodesFromComponentSpec.test.ts

Adds a simple annotation editor to the TaskNode config sheet via a new "Annotations" tab.
Works similar to the argument editor, but allows custom string fields to be added as annotations in the TaskSpec.
Annotations can also be removed (except `editor.position` since this is used to position the node on the canvas).
Changes to the annotations are committed once "Apply" is clicked. Once applied an annotation's key cannot be changed, but its value can still be edited.

Add Simple Annotation Editor to Task Nodes

---

src/components/Editor/PipelineEditor.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowControls/FlowControls.tsx
src/components/shared/ReactFlow/FlowControls/index.ts
src/components/shared/ReactFlow/index.ts
src/styles/editor.css

Adds a button to the Canvas toolbar to toggle the selection mode in and out of multi select. When in multi-select mode the cursor will change to a crosshair and behave the same as if shift was being held down (i.e. click and drag will create a selection toolbox)

Add Toggle for MultiSelection on the Canvas

---

src/services/pipelineRunService.ts
src/utils/constants.ts

Fixes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/265

chore: Add the "editor.flow-direction: left-to-right" annotation to new and cloned pipelines

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/TaskDetails/Details.tsx
src/hooks/useCopyToClip.ts

This PR merges the YAML tab into the Details tab for both pipelines and runs. 
Rather than hard-coding each section and conditionally rendering based on various combinations of values, this PR introduces a more flexible pattern. The additionalSection prop enables:
- Modular addition of content that's not part of the core details
- Future extensibility without modifying the base component
- Cleaner separation of concerns between core and supplementary information
The Component YAML is the first implementation of this pattern, but this approach allows the component to evolve organically as new requirements emerge.
I've also made digest "click to copy" so we could truncate its long text. I had to do this because when the YAML section is open it creates a scroll bar and the digest text gets …

This PR merges the YAML tab into details

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/ComputeResourcesEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/155
First iteration of an explicit Compute Resources section in the annotation editor.
Compute Resources will also be visible, even if empty. When a value is entered and "Apply" click it will be written to the task annotations.
This is a quick and rough first-iteration, so UX and code refinement will be needed in the future.

Add Compute Resources section to Annotation Editor

---

src/components/layout/EditorMenu.tsx
src/hooks/useDocumentTitle.ts
src/routes/PipelineRun/PipelineRun.tsx

This PR cleans up the default titles for each page to make information more clear. I have also updated the `src/components/layout/EditorMenu.tsx` component to include the runs name and ID, similar to what we have on the editor
Editor:
Runs Details:

Adds title to the run details page

---

src/components/layout/EditorMenu.tsx
src/components/shared/CloneRunButton.tsx
src/hooks/useLoadComponentSpecDetailsFromId.ts
src/routes/PipelineRun/PipelineRun.tsx

We were seeing a few failed API calls because we were trying to call the run details, on the pipeline editor, which would not work because its not a run and has no run ID. I've also fixed some bad react code I wrote.

This PR cleans up the API errors we are seeing

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsSection.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/utils.ts
src/services/pipelineRunService.ts

Duplicate tasks using `structuredClone` instead of JSON transform.
ArgumentsSection and ArgumentsEditorDialog now organize argument info in the same way via a shared utility.
No change to app functionality

Minor Arguments cleanup

---

package-lock.json
package.json
src/components/shared/ReactFlow/FlowSidebar/components/SearchFilter.tsx
src/components/shared/ReactFlow/FlowSidebar/components/SearchInput.tsx
src/components/shared/ReactFlow/FlowSidebar/components/SearchResults.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/GraphComponents.tsx
src/components/ui/checkbox.tsx
src/types/componentLibrary.ts
src/utils/constants.ts

Adds a filter to the Component Search, allowing the user to search across component Name, Inputs and Outputs. By default the filter is set to "Name", which mirrors the current search behaviour. Users can then open the popover to configure which fields they want to apply their search to.
When a search is being conducted the filter button will display how many fields are being searched. If no filter is set the user will be prompted to search by name.
The filters do not apply if not search term is entered. i.e. they are strictly related to the fields being searched and not general filtering of the component library.
Note: the UX isn't quite where I want it, but this will do as as first step for now. (having filters that only apply to a search result but act more as search fields than filters …

Allow Search Filtering by Inputs and Outputs

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeOutputs.tsx

Makes I/O handles (the circles) selectable and implements a framework to trigger a callback when selected (currently no callback is given). When selected the handle and label will highlight blue. Note that clicking on the label will open the argument editor as per existing behaviour.
Additionally, introduces an `active` state to Handles, making them highlight when an active connection is being made involving them.
Finally, fixes a big that led to inconsistent behaviour when clicking on Inputs vs Outputs.
This PR is intended to be a stepping stone that follows #299, with the intention of eventually allowing the component library to be filtered when a node is selected or active.
https://github.com/user-attachments/assets/1fe4e2d6-b187-498d-a0f7-0cd16ed8b248

Highlight Input/Output Handles

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/hooks/useComponentUploader.tsx
src/hooks/useImportComponent.ts
src/utils/componentStore.ts

When a user drops a component.yaml on the canvas we now add the component to the canvas as well.
Some of the code lives in the FlowCanvas.tsx file, which will be moved out in a later effort to clean up that file.
Note: There will be another PR that checks if the node shares a name, but not the exact content, with another and prompts the user to replace, create new, or cancel. 
https://github.com/user-attachments/assets/186f035c-3ba8-4324-8b9d-ab6e9ef4e558

Dropped components yaml now appear on canvas

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/ioCell.tsx

This is a fix for how the artifacts cell renders.
Before (you can see the text overflows)
After:
Also if the name is long
If the name is long but there is no artifact
If the name is long and so is the artifact

Fixes rendering of artifacts that are long

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeOutputs.tsx

Two super-quick fixes to task cards:
1. fixes for app crash when a card has no inputs of outputs
2. fixes a card being expandable when all fields are already displayed

Quick fixes to TaskCard UX

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Prevents an Input Handle from being connected to an Output Handle on the same node.
Note: only blocks drawing the connection on the graph - the user can still choose to manually enter the connection in the arguments editor

Prevent TaskNodes from being connected to themselves

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeOutputs.tsx
src/utils/searchUtils.ts

Follows #316 
Clicking on an Input or Output Handle will highlight other Handles on the Canvas that will accept the same data type. Dragging an edge from a Handle will also do the same.
i.e. clicking on an output with type `csv` will highlight all input handles that accept `csv` input.

Highlight related I/O Handles when selected or dragged

---

src/components/Editor/PipelineEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsInput.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowSidebar/FlowSidebar.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ImportComponent.tsx
src/components/shared/ReactFlow/FlowSidebar/components/UserComponentItem.tsx
src/components/ui/sidebar.tsx

Moves the Sidebar to the left of the screen and resizes it to make it a little narrower. The TaskConfigSheet is also made narrower so that together both components don't consume too much screen space.
Further follow-ups will be needed to refine some internal component sizes, such as the annotation editor input boxes.
Also, a follow-up will be needed to turn the ConfigSheet into a more permanent right-side sidebar that holds element/node/spec context.

Move Sidebar to left of Screen

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentInputField.tsx
src/utils/componentSpec.ts

hints should be read from input annotations, not the input itself

Fix incorrectly applied input hint definition

---

src/components/Editor/PipelineDetails.tsx
src/components/Editor/PipelineEditor.tsx
src/components/Editor/RenamePipeline.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/components/PipelineRun/RunDetails.tsx
src/components/layout/AppMenu.tsx
src/providers/ComponentSpecProvider.tsx
src/providers/ContextPanelProvider.tsx
src/routes/Editor/Editor.tsx
src/routes/PipelineRun/PipelineRun.tsx

Behind-the-scenes work and scaffolding of a basic details panel for the Pipeline Editor and Runs page.
Edit Pipeline name functionality moved to the PipelineDetails panel.
Run status indicator shown in RunDetails panel.
Follows https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/355
Pipeline Editor:
Run Page:
Issues will be created to outline the full set of content desired in each of the two new details panels.

Scaffold pipeline details

---

src/components/Editor/PipelineDetails.tsx
src/components/layout/AppFooter.tsx
src/components/layout/AppMenu.tsx
src/components/shared/CodeViewer.tsx
src/components/shared/ContextPanel/ContextPanel.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/RunsAndSubmission.tsx
src/components/shared/RunOverview.tsx
src/components/shared/Status/StatusText.tsx
src/components/shared/TaskDetails/Implementation.tsx
src/hooks/useExecutionStatusQuery.ts
src/utils/constants.ts

Populates the right-side context panel in the Pipeline Editor with pipeline details such as file metadata, digest, annotations, execution history and YAML.
Also includes minor updates to the RunOverview and Status update components.
Follows #402 
Note this is a detailed outline of content that could be in the panel. As we refine what we want in there the design will improve and we will likely start breaking sections out into their own component. This will also present the opportunity to clean up some of the AI-generated html.
Note: in future, we may want to consider the merit of having run submission details still in the left sidebar now that we have them on the right & have more space there.
Second note: this introduce a potential performance/network issue which will be addressed as a …

Add Pipeline Details to Pipeline Editor Context Panel

---

src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx

User components are now removed via the "unstar" feature so the delete button in the modal is no longer needed.
Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/311
n/a
n/a

Remove unneeded Delete Component button

---

src/components/Editor/PipelineDetails.tsx
src/components/Editor/PipelineEditor.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/components/shared/ContextPanel/CollapsibleContextPanel.tsx

The right-side context panel is now collapsible.
https://github.com/Shopify/oasis-frontend/issues/114
Note a floating icon to the left of the panel, similar to the one to the left of the sidebar, was not possible due to the way ResizablePanel works.

Collapsible Context Panel

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsInput.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/ComputeResourcesEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentInputField.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/OutputsList.tsx

Now that the task config is int he context panel, and the context panel can be resized, the arguments editor needs updating to make use of the extra space. The input fields will now grow to fill the available space.
The annotations editor has similarly been updated as well.
Closes https://github.com/Shopify/oasis-frontend/issues/116
n/a

Grow Argument Input Fields

---

src/providers/ContextPanelProvider.tsx

This PR removes the effect that caused the context panel to re-render different states when you drag a node, causing very poor performance.
This pull request removes an unnecessary `useEffect` hook from the `ContextPanelProvider` component in `src/providers/ContextPanelProvider.tsx`. The hook previously reset the `content` state to `defaultContent` whenever `defaultContent` changed, but this behavior is no longer needed.

Fix slowness when dragging nodes

---

src/components/Editor/PipelineEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/GhostNode/HintNode.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx
src/hooks/useHintNode.ts
src/types/hintNode.ts

Follows #315 as a step toward adding new components when dragging edges.
Adds a new HintNode type that appears when dragging an edge. The `key` and `hint` text can be customized via a new useHintNode hook.
This PR utilizes it to add a little "tab" key indicator next to the cursor when the user is dragging an edge and the handle they dragged from has produced search results. The intent in a future PR is to allow the user to press tab to cycle through these results and create a node on the spot when they release the edge. 
Since this currently isn't implement an override has been added to hide the Tab Indicator for now. So, essentially this PR just lays some groundwork for future implementation.
https://github.com/user-attachments/assets/05715dee-20ec-4148-9d9a-626972e6b16a

Add TAB HintNode when dragging new Edges

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/addAndConnectNode.ts
src/hooks/useTaskNodeDimensions.ts
src/utils/constants.ts

Final PR in the UX Quest to add TaskNodes while dragging edges.
This PR adds a new method `addAndConnectNode` that adds a new node to the canvas and connects it to a given handle. This is used to implement the ability for Ghost Nodes to become fully functional Task Nodes when dropped on the canvas.
Follows #342
https://github.com/user-attachments/assets/a365f736-7351-4336-9588-7bdd03a53efa
https://github.com/user-attachments/assets/9c165cac-74b5-422f-9402-e1d1156d140a
There will be a followup PR somewhere in the future where the ghost node is positioned with the edge pointing into the correct handle, rather than the top left/right.

Convert GhostNodes into TaskNodes when dropped

---

src/components/Editor/PipelineDetails.tsx
src/components/PipelineRun/RunDetails.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/components/shared/Status/StatusIcon.tsx

A minor PR to add the option for tooltips on status icons. Also adds an icon for `SKIPPED`
Also fixes a bug where icons could overflow the sidebar toggle button on the right-side context panel.
n/a
n/a
no significant changes to app functionality

Improvements to StatusIcon

---

src/components/shared/CodeViewer/CodeViewer.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/logs.tsx
src/components/shared/TaskDetails/Details.tsx

Some css changes to make the log viewer fill the available space, rather than overflowing off the bottom of the context panel.
Closes https://github.com/Shopify/oasis-frontend/issues/128

Bugfix logs panel codeviewer css

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/utils.ts

Fixes an unintended bug introduced or overlooked in #456 where unset arguments with no value could not be set.

Fix bug where empty arguments can not be set

---

src/components/shared/TaskDetails/Details.tsx
src/utils/URL.ts

This PR updates the component URL format in the Task Details view to use GitHub's web interface URLs instead of raw content URLs. When displaying component links, the URL format is changed from `https://raw.githubusercontent.com/.../SHA/...` to `https://github.com/.../blob/SHA/...`. This provides a better user experience as users will see the GitHub UI with syntax highlighting, navigation options, and other GitHub features instead of plain text.
The change only affects the URL reconstruction logic when the `url` prop is not provided and the URL needs to be built from git metadata annotations.
**Before:** Links pointed to raw GitHub content (plain text view)
`https://raw.githubusercontent.com/Shopify/discovery/f3e61a928f6fec914f421d509e39081e8a62b240/relevance-tools/src/relevance_tools/oasi …

fix: Fixed raw github URL generation

---

src/components/Editor/PipelineDetails.tsx
src/components/Editor/components/RecentExecutions.tsx
src/components/shared/RunOverview.tsx
src/components/shared/Status/StatusText.tsx
src/components/shared/Status/TaskStatusBar.tsx
src/providers/PipelineRunsProvider.tsx
src/services/executionService.test.ts
src/services/executionService.ts
src/types/pipelineRun.ts

Fixes an issue where the PipelineDetails context panel was refetching execution status info every time the panel rendered (i.e. after deselecting a node).
The relevant execution data is now fetched in PipelineRunsProvider when the page is loaded and provided to the panel so it does not need to fetch the data itself.
To keep initial load times reasonable it is now possible to specify how many recent executions the additional data will be fetched for. The execution info in the context panel will display this number of executions, with the remainder being relegated to "+X more executions" and not (currently) accessible.
This also mitigates somewhat the previous error spam in the console when an execution could not be found: now the run (without status) will be returned so at least we can …

Populate PipelineDetails Executions on Initial Load

---

src/providers/ComponentLibraryProvider.tsx
src/utils/componentLibrary.ts

Component library will now load component refs first by spec, then by text, and only then by url.
Related: https://github.com/Shopify/oasis-frontend/issues/146

Populate Component Refs from Spec and Text before Url

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx

Reverses the CSS changes that slipped in [here](https://github.com/Cloud-Pipelines/pipeline-studio-app/commit/943267d4da6a1296c37ae5bc617cc5cca5a5bb29#diff-4348f37088bf0541544ff44ada9198fe06bd156e03b80be9094916fc29f7690dR60-R61) so that the logs are now full-height again.

Fix Logs being Squashed

---

package.json
src/components/Editor/InputValueEditor/FormFields/FormFields.test.tsx
src/components/Editor/InputValueEditor/FormFields/FormFields.tsx
src/components/Editor/InputValueEditor/FormFields/index.ts
src/components/Editor/InputValueEditor/FormFields/utils.ts
src/components/Editor/InputValueEditor/InputValueEditor.test.tsx
src/components/Editor/InputValueEditor/InputValueEditor.tsx
src/components/Editor/OutputNameEditor/OutputNameEditor.tsx
src/components/Editor/OutputNameEditor/index.ts
src/components/Editor/PipelineDetails.tsx
src/components/PipelineRun/components/CancelPipelineRunButton.test.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/IONode/IONode.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/getArgumentsFromInputs.ts
src/components/shared/ReactFlow/FlowCanvas/utils/getOutputConnectedDetails.ts
src/components/shared/ReactFlow/FlowCanvas/utils/setGraphOutputValue.test.ts
src/components/shared/ReactFlow/FlowCanvas/utils/setGraphOutputValue.ts
src/components/shared/ReactFlow/FlowCanvas/utils/updateInputNameOnComponentSpec.ts
src/components/shared/ReactFlow/FlowCanvas/utils/updateOutputNameOnComponentSpec.test.ts
src/components/shared/ReactFlow/FlowCanvas/utils/updateOutputNameOnComponentSpec.ts
src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/FolderItem.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/GraphComponents.tsx
src/providers/PipelineRunsProvider.tsx
src/styles/editor.css
src/types/componentLibrary.ts
src/utils/componentSpec.ts
src/utils/inputConnectionUtils.ts
src/utils/nodes/createNodesFromComponentSpec.ts

Closes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/25
This PR lets users drag "special" nodes like input and output nodes to the graph where they can:
- Attach to the input or output of existing nodes
- Rename the nodes
- Change the type, which is mainly for the UI to help facilitate better UI such as date picker or boolean
- Change the value of an input node
- Export a pipeline and use it as a component
I have colour coded the nodes to blue and purple, which is a slight departure from cloud pipelines where they were blue and red. I didn't want the output to be red because that signifies an error.
None issues: Multi-select with IO nodes doesn't quite work. This will be fixed in a fast followup
**COPILOT:**
This pull request introduces significant enhancements to the …

Users can update pipeline inputs

---

src/components/layout/AppMenu.tsx
src/components/layout/RootLayout.tsx
src/components/shared/BackendStatus.tsx
src/providers/BackendProvider.tsx

Wraps the app in a BackendProvider that provides the app with the ability to ping the backend to see how it's doing. This is then used to display the backend status on the menu bar. Click the status to ping the backend for an update (will be changed in a later PR to open a dialog where backend url can be edited)
Progresses https://github.com/Shopify/oasis-frontend/issues/133
This will be developed in further PR's into a system where users without a backend will be prompted to configure their own one. At the moment this PR is intended to provide a foundation or skeleton to work from.

Add BackendProvider and show Status in Menu

---

src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx

https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/485 removed outdated autosave logic which had proven to be buggy. This PR removes some additional code that had been added to circumvent errors that were caused by the old autosave feature. Now that the feature has been removed we no longer need the workaround code.
Additionally, we now have a new autosave feature and the workaround is now potentially a detriment that is causing the export pipeline feature to print empty yaml files after a pipeline has been reloaded.
The exact cause is not known (on of the boolean conditions in the if statement must be failing), but it is possible that with additional node types recently added the task/node length check is the culprit.
This PR will be immediately pushed through to staging for …

Potential Fix for Empty Pipeline Exports on Staging/Production

---

src/components/shared/BackendStatus.tsx
src/components/shared/Dialogs/BackendConfigurationDialog.tsx
src/providers/BackendProvider.tsx
src/utils/URL.test.ts
src/utils/URL.ts
src/utils/localforage.ts

Implements a dialog where the user can configure a backend url and test it.
NOTE: this does not propagate the entered backend url through to fetch methods and such. That functionality will come in the next PR.
Also includes a toggle to use the config from the env file, or override it with a user-entered value.
Progresses https://github.com/Shopify/oasis-frontend/issues/133

Backend Configuration Dialog

---

src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/RunDetails.tsx
src/services/executionService.ts

resolves: https://github.com/Shopify/oasis-frontend/issues/143
This PR fixes an issue where the run status wasn't updating. You can use
Copilot:
This pull request introduces enhancements to the `RunDetails` component and related services, focusing on improving polling functionality, integrating the `ComponentSpecProvider`, and refining error handling. The changes primarily affect the `RunDetails` component, its corresponding test file, and the `executionService`.
* [`src/components/PipelineRun/RunDetails.tsx`](diffhunk://#diff-e0f565b9451ffdc2507ef5c334dbe20d0e726b8211b79830703b77a8913e2da7R29-R44): Added polling control via the `isPolling` state and updated the `fetchExecutionInfo` function to use the `poll` parameter for dynamic refetch intervals. Polling stops automatically when the …

Adds polling to status on side bar

---

src/components/shared/Dialogs/BackendConfigurationDialog.tsx
src/providers/BackendProvider.tsx
src/utils/localforage.ts

Follows #551 to allow the backend to be configured relative to the frontend url if there is no env variable. this is needed to keep the app functioning on staging & production, as env variables are not available there and they are configured relative to the domain.
When there is no env defined the system will instead attempt to use a relative backend url.
Also cleans-up some of the experimentation I was doing on staging.

Configure Backend By Relative URL

---

src/providers/BackendProvider.tsx

the `normalizeUrl` function doesn't know if the url is meant to be a relative path. so for relative paths we now convert to absolute by substituting in the current domain.

Fix Relative Path URL giving wrong status

---

src/hooks/useLoadComponentSpecFromId.ts

Fixes a bug where pipeline spec was not unloaded when the pipeline was closed, resulting in the clone button returning the wrong pipeline and potentially other downstream issues.
Closes https://github.com/Shopify/oasis-frontend/issues/168
tbc https://github.com/Shopify/oasis-frontend/issues/169

Fix Spec not unloading when pipeline is closed

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/logs.tsx

Polling every 1s could be an issue for large logs. Changing to 5s.
Also removes `isFetching` which was causing it to flicker between logs and loading state. Another solution will be needed when reloading logs due to a change in backend url.

Extend log polling to 5s

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/TaskDetails/Details.tsx

Fixes an issue where the callbacks passed into a task node were memoized with stale `nodes` array references on first render, meaning that an operation would not succeed.
The callbacks will now fetch the nodes array when called rather than relying on a memoized value.
Closes https://github.com/Shopify/oasis-frontend/issues/169

Fix Task Node buttons not working due to stale nodes reference

---

src/components/Home/RunSection/RunRow.tsx
src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/RunDetails.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/io.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/providers/ContextPanelProvider.tsx
src/routes/PipelineRun/PipelineRun.tsx
src/services/executionService.ts

Closes https://github.com/Shopify/oasis-frontend/issues/176
Fixed several React hook-related issues:
- Removed an unnecessary duplicate effect in TaskNodeCard that was causing the same content to be set twice
- Eliminated a redundant refetch in the io.tsx component
- Optimized the ContextPanelProvider with useCallback and useMemo to prevent unnecessary re-renders
- Renamed `fetchExecutionInfo` to `useFetchExecutionInfo` to better reflect that it's a React hook.
One of the issues was a loop between `ContextPanelProvider` and `TaskNodeCard` where it tried to `setContent` multiple times.
Verify that pipeline runs and execution information still load correctly throughout the application, particularly in the RunRow, RunDetails, and PipelineRun components.

fix infinite loop loading artifacts

---

.prettierrc

Added a `.prettierrc` configuration file to standardize code formatting across the project. 
I noticed, that VSCode formats slightly differently compared to CLI, even though the version of prettier is the same. Having configuration explicit helps to avoid divergence.
The configuration specifies:
- Trailing commas for all multi-line structures
- Tab width of 2 spaces
- Semicolons required
- Double quotes preferred over single quotes
1. Run `prettier --write .` to verify the new configuration is applied correctly
2. Check that your IDE's Prettier integration picks up the new configuration
This standardization will help maintain consistent code style across the codebase and reduce formatting-related merge conflicts.

Explicit prettier config

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Added a clear content of the side panel when node is removed in the FlowCanvas component. 
1. Open a flow with elements
2. Delete an element
3. Verify that the content is properly cleared after deletion
https://github.com/user-attachments/assets/8d1a2c5a-30c3-461b-9d9a-da859c98ce51

fix side panel sync on node remove

---

src/components/PipelineRun/PipelineRunPage.tsx
src/components/PipelineRun/RootExecutionStatusProvider.test.tsx
src/components/PipelineRun/RootExecutionStatusProvider.tsx
src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/RunDetails.tsx

Closes https://github.com/Shopify/oasis-frontend/issues/179
Added a new `RootExecutionStatusProvider` to centralize pipeline run execution status management. This provider fetches and maintains execution information, handles polling logic, and exposes execution details through a context API.
The implementation includes:
- A context provider that manages execution status data
- Automatic polling that stops when execution completes
- Comprehensive test coverage for the new provider
- Refactored `RunDetails` component to consume the context instead of managing its own state
1. Navigate to any pipeline run page
2. Verify that run details are displayed correctly
3. For in-progress runs, verify that status updates automatically
4. For completed runs, verify that polling stops appropriately …

fix run status polling behavior

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx

Fixes a recently introduced bug where the context panel would not reset to default when the selected node is deleted.
Bugfix for #606

Fix bug where context panel did not update when a node is deleted

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/hooks/useConfirmationDialog.ts
src/hooks/useNodeCallbacks.ts

Just moving some code to improve readability and reduce the size of FlowCanvas.tsx. To facilitate this the `getNodesById` method is shifted to rely on `reactFlowInstance`, rather than `setNodes`.
No (intended) change to app functionality

Move Node Callbacks into a Hook

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/logs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/tests/logs.test.tsx
src/components/ui/link.tsx

Added a "Open in new tab" link for task logs, allowing users to view logs in a separate browser tab. This feature enhances the user experience by providing a more flexible way to view execution logs, especially for longer log outputs.
Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/144
| Screenshot | Use-case |
|--------|--------|
| <img width="515" height="1272" alt="image" src="https://github.com/user-attachments/assets/b8c3cec2-8d71-405a-9c25-1727c489b844" /> | Base use-case - show link to open logs |
| <img width="515" height="1272" alt="image" src="https://github.com/user-attachments/assets/1f105465-e767-4716-803e-e0ec5ffa5105" /> | Logs are loading,  but link is always available |
| <img width="515" height="1272" alt="image" …

Add open raw logs to run details

---

package-lock.json
package.json
src/components/shared/CodeViewer/CodeSyntaxHighlighter.test.tsx
src/components/shared/CodeViewer/CodeSyntaxHighlighter.tsx
src/components/shared/CodeViewer/CodeViewer.tsx

Closes https://github.com/Shopify/oasis-frontend/issues/93
Virtualization works on an editor level, making overall viewing experience smoother and performant
Legacy experience (virtualization via slicing data in re-rendering CodeViewer) - we see chopped visualization and FPS drops to ~10-16:
https://github.com/user-attachments/assets/660bcda5-6c34-4779-9e9c-315f59e73dbb 
Tanstack Virtual inside the syntax highlight code viewer - FPS holds around 50-60:
https://github.com/user-attachments/assets/dbd7f4dc-3da4-4745-9e5c-97e0ab22f33e 
| Legacy | New |
|--------|--------|
| <img width="611" height="535" alt="LEgacy profiling" src="https://github.com/user-attachments/assets/3b1b03c8-bc8c-4dc9-8a1c-d80d86f5b61a" /> | <img width="609" height="611" alt="Tanstack profiling" …

Tanstack embedded virtualization for SyntaxHighlighter

---

src/betaFlags.ts
src/components/shared/CodeViewer/CodeSyntaxHighlighter.tsx
src/components/shared/CodeViewer/CodeViewer.tsx
src/components/shared/FullscreenElement/FullscreenElement.test.tsx
src/components/shared/FullscreenElement/FullscreenElement.tsx
src/components/shared/FullscreenElement/index.ts

The `FullscreenElement` component provides seamless fullscreen functionality for any React content while preserving component state and optimizing performance through intelligent DOM manipulation. The change is behind the beta flag.
- Acts instantly - no delays for heavy-computational components.
- Component state, form inputs, scroll positions, and all internal state are preserved during fullscreen transitions
- Content is only re-rendered when children actually change, not on every fullscreen toggle
- Existing DOM elements are reused - nothing is recreated during transitions
This approach allows to replace convoluted Provider based existing solution, where we creating duplicates of the components.
Closes https://github.com/Shopify/oasis-frontend/issues/124 …

Inline fullscreen element

---

src/appSettings.ts
src/hooks/useComponentFromUrl.ts
src/services/componentService.test.ts
src/services/componentService.ts
src/utils/componentLibrary.ts
src/utils/localforage.ts

Add priority order to component fetching and storing. First by text, then url, then spec.
Fixes https://github.com/Shopify/oasis-frontend/issues/146

Fetch and Store components by Text > Url > Spec

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/logs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/tests/logs.test.tsx

Contributes to https://github.com/Shopify/oasis-frontend/issues/171
Removed task statuses `PENDING`, `QUEUED`, and `WAITING_FOR_UPSTREAM` from the list of statuses that are considered to be actively logging. Now only `RUNNING` and `CANCELLING` statuses will trigger active logging behavior.
Verify that logs are only actively fetched for tasks with `RUNNING` or `CANCELLING` status, and not for tasks with `PENDING`, `QUEUED`, or `WAITING_FOR_UPSTREAM` status.

do not poll logs when status not appropriate

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/ioCell.tsx

This pull request updates the way JSON artifact data is displayed in the `IoCell` component, improving both the code structure and the user interface. The main changes include switching to a new `CodeViewer` component, limiting the display height for large JSON values, and ensuring better UI handling for overflowing content.
**UI and Display Improvements:**
* Replaced the older `CodeSyntaxHighlighter` with the new `CodeViewer` component for displaying JSON artifact data, and wrapped it in a container with a calculated maximum height to prevent large outputs from overflowing the UI. [[1]](diffhunk://#diff-c8b80cdb5e8b1ccd48eac5c5a43dfed571341015e6a61f9f7660ed2d389e6a28L4-R4) [[2]](diffhunk://#diff-c8b80cdb5e8b1ccd48eac5c5a43dfed571341015e6a61f9f7660ed2d389e6a28R200-R218)
* Added logic to …

Dynamically set the height of the code viwer in artifacts

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx

Patches over a critical issue that was causing the app to crash when dragging nodes. The issue has multiple causes, all triggered by the drag operation and potential updates to annotations/arguments causing infinite rerenders of the context panel. This was made even worse when multiple nodes are selected as they begin competing for the context panel space. The issue was NOT observed on IO nodes, or on nodes with no upstream connections. However, it was observed in any scenario involving connected or unconnected nodes that have been multi-selected. The symptom of the issue is the context panel being infinitely updated while a drag operation takes place, but the cause of this is currently unknown.
This PR patches over it by disabling context panel updates while a node is being dragged. It …

Disable Context Panel Updates when Dragging Nodes

---

src/services/componentService.test.ts
src/services/componentService.ts
src/utils/localforage.ts

Closes https://github.com/Shopify/oasis-frontend/issues/203
Improved component storage logic to prevent overwriting existing components unnecessarily. The changes ensure that when fetching and storing components, we check if a component with the same ID already exists and only update it if the content has changed. This preserves existing component state while avoiding redundant storage operations.
1. Test loading components from a library multiple times to verify they aren't unnecessarily overwritten
2. Verify that component state is preserved when re-fetching existing components
3. Run the updated tests to confirm the new behavior works as expected
https://github.com/user-attachments/assets/4833783f-e843-4f5d-99f0-0c5bd284383b

fix broken add to favorite

---

src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/ReplaceConfirmation.tsx

Fixes and issue where text would overflow off the dialog when argument values are very long.
Solution is not _amazing_ but it will do for now as a quick fix.
Closes https://github.com/Shopify/oasis-frontend/issues/208
Before:
After:

Fix long argument strings overflow replace dialog

---

src/components/shared/ReactFlow/FlowCanvas/utils/updateNodePosition.ts

Fix a bug where only the last IO node in a group of nodes will have its position updated.
Progresses Shopify/oasis-frontend#148
1. Create a group of IO nodes on the canvas
2. Select the group using multi-select
3. Move the group to a new location on the canvas
4. Nodes will move to new location (compare: on current master/production all but one will return to their original position)

Fix IO Node Positioning Bug

---

src/utils/nodes/createInputNode.ts
src/utils/nodes/createNodesFromComponentSpec.ts
src/utils/nodes/createOutputNode.ts

Moves IO node creation into separate methods so they can be reused by IO duplication actions (similar to task nodes).
No change to app functionality; just setting up for IO node duplication functionality.
Progresses https://github.com/Shopify/oasis-frontend/issues/148
1. confirm that IO nodes work exactly the same as before

CreateInputNode and CreateOutputNode Methods

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/duplicateNodes.test.ts
src/components/shared/ReactFlow/FlowCanvas/utils/duplicateNodes.ts
src/hooks/useNodeCallbacks.ts

Adds support for duplicating input nodes via node toolbar "duplicate" button and Copy + Paste.
Input node duplication follows similar logic to the existing task duplication, including support for different connection modes when duplicating groups of nodes (task and/or input) on the canvas.
Progresses https://github.com/Shopify/oasis-frontend/issues/148
1. create a pipeline with some input nodes
2. select a group of nodes, including input nodes
3. copy + paste or duplicate the selection
The existing node duplication method iterates on graphSpec. However, IO nodes are defined at the componentSpec level, so the associated methods have been revised to iterate on componentSpec rather than graphspec.

Input Nodes can now be Duplicated

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/handleUtils.test.ts
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/handleUtils.ts

Formats input value label on nodes to node be a json string.
Follows #751

Format Input Values on Nodes

---

package-lock.json
package.json
src/components/shared/SuspenseWrapper.test.tsx
src/components/shared/SuspenseWrapper.tsx
src/components/ui/spinner.tsx

Added a new `SuspenseWrapper` component and `withSuspenseWrapper` HOC to handle React Suspense and error boundaries in a consistent way across the application. This implementation:
- Provides a reusable wrapper for components that might suspend or throw errors
- Includes a default loading state with a spinner
- Supports custom fallback components
- Handles error states with a "Try again" button for recovery
- Integrates with React Query's error reset boundary
1. The component is fully tested with comprehensive test cases
2. To manually test, wrap any component that uses suspense or might throw errors:
3. Or use the HOC pattern:

suspense wrapper

---

src/betaFlags.ts

Added a new beta flag for remote component library search functionality. This flag will enable users to search for components in remote libraries.
1. Enable the "remote-component-library-search" beta flag
2. Verify that the remote component library search functionality becomes available
3. Test searching for components in remote libraries
The beta flag is disabled by default and can be enabled for testing purposes.

remote components search beta flag

---

src/hooks/useHydrateComponentReference.test.tsx
src/hooks/useHydrateComponentReference.ts
src/services/componentService.ts
src/services/hydrateComponentReference.test.ts
src/utils/componentSpec.ts

Added a new hook `useHydrateComponentReference` to fetch and hydrate component references from URLs or local storage. This hook uses React Query for data fetching with 1-hour caching to improve performance.
Also implemented the underlying `hydrateComponentReference` service function that handles the actual component hydration logic, including:
- Fetching component specs from URLs
- Parsing YAML text into component specs
- Generating digests for components
- Caching components in local storage
- Handling various error cases
```
flowchart TD
Start([start]) --> S1{Strategy 1:<br/>isInvalidComponentReference?}
S1 -->|YES<br/><br/>Returns null| ReturnNull[Return null]
S1 -->|NO| S2
S2{Strategy 2:<br/>isHydratedComponentReference?} 
S2 -->|YES<br/><br/>All fields already present:<br/>• text: …
```

hydrate component reference

---

src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx

Fixes an issue where the "Export pipeline" button was exporting outdated pipelines (i.e. ignoring the most recent edits)
Closes https://github.com/Shopify/oasis-frontend/issues/221

Bugfix Export Pipeline button using outdated spec

---

src/components/Editor/RenamePipeline.tsx

Fixes an issue where renaming a pipeline results in the user being redirected to the new pipeline URL but with an outdated spec. It also fixes a related issue where renaming a pipeline may create a clone of the pipeline rather than editing the existing version.
The issue was caused by the renaming function not including an explicit save call for the spec with the updated name. Previously it was relying on the autosave feature but as this has been updated and changed over time it was no longer fit for this purposes. An explicit save has now been added after the pipeline file has been renamed.
Closes https://github.com/Shopify/oasis-frontend/issues/220

Fix Pipeline Rename Operation Resulting in Clones

---

src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/ManageComponent/ComponentHistoryTimeline.tsx
src/components/shared/ManageComponent/ComponentQualityCard.tsx
src/components/shared/ManageComponent/ComponentQuickDetailsDialog.tsx
src/components/shared/ManageComponent/ComponentSpecProperty.tsx
src/components/shared/ManageComponent/ComponentUsageCount.tsx
src/components/shared/ManageComponent/DeprecatePublishedComponentButton.tsx
src/components/shared/ManageComponent/PublishComponent.test.tsx
src/components/shared/ManageComponent/PublishComponent.tsx
src/components/shared/ManageComponent/PublishComponentButton.tsx
src/components/shared/ManageComponent/TrimmedDigest.tsx
src/components/shared/ManageComponent/hooks/useComponentCanvasTasks.ts
src/components/shared/ManageComponent/hooks/usePublishedComponentHistory.ts
src/components/shared/ManageComponent/hooks/useUserDetails.ts
src/components/shared/ManageComponent/types.ts
src/components/shared/ManageComponent/utils/digest.ts
src/components/shared/ManageComponent/utils/user.ts
src/components/shared/ReactFlow/FlowSidebar/components/FolderItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/PublishedComponentsSearch.tsx
src/utils/componentSpec.ts
tests/e2e/fixtures/components/test-component-a.component.v1.yaml
tests/e2e/published-componentlifecycle.spec.ts

Added a new "Publish" tab to the Component Details Dialog that allows users to publish components to a shared library. This feature enables component sharing across the workspace, making components discoverable and reusable by other users.
The implementation includes:
- A new PublishComponent component with component history timeline
- Component quality checks to ensure published components are well-documented
- Ability to release new versions of components and deprecate existing ones
- User details utility for tracking component authorship
https://github.com/user-attachments/assets/31dd1221-4df4-49f2-af25-756b36480105
1. Open a component in the Component Details Dialog
2. Navigate to the new "Publish" tab
3. Review component details and publish history
4. Test publishing a component, …

publish component from my components

---

src/components/Home/PipelineSection/BulkActionsBar.tsx
src/components/Home/PipelineSection/PipelineRow/PipelineRow.tsx
src/components/Home/PipelineSection/PipelineSection.tsx
src/services/pipelineService.ts
src/utils/string.ts

Adds checkboxes and bulk actions to the pipeline list. Users can now select multiple pipelines and delete them.
Bulk actions are access by an action bar that appears at the bottom of the screen when some checkboxes have been selected
User requested
1. Navigate to the pipeline list
2. select some pipelines using the checkboxes
4. delete the pipelines
5. (de)select all using the checkbox at the top of the table

Bulk Actions on Pipeline List

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsSection.tsx

Moves the "new" button that adds a new empty annotation row to the header. Behaviour is otherwise unchanged.

Move New Annotation Button to Section Header

---

src/routes/Editor/Editor.tsx

Adds an error page to pipelines that have an error when loading e.g. the pipeline does not exist at the given url
This is most useful when users try to share pipelines via url, as they are stored locally so trying to load them from a url won't work (currently results in an infinite loading spinner)
n/a
1. load a pipeline from your list. success
2. modify the url so it does not match any pipelines you have. error page

Error page for Pipeline Editor

---

src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/Dialogs/dialog.context.tsx
src/components/shared/ManageComponent/ComponentHistoryTimeline.tsx
src/components/shared/ManageComponent/PublishedComponentBadge.tsx
src/components/shared/ManageComponent/PublishedComponentDetails.tsx
src/components/shared/ManageComponent/hooks/useAllPublishedComponents.ts
src/components/shared/ManageComponent/hooks/useForceUpdateTasks.ts
src/components/shared/ManageComponent/hooks/useHasPublishedComponent.ts
src/components/shared/ManageComponent/hooks/useOutdatedComponents.ts
src/components/shared/ReactFlow/FlowCanvas/ConfirmationDialogs/UpgradeComponent.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/UpgradeNodePopover.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/replaceTaskNode.ts
src/components/shared/ReactFlow/NodesOverlay/NodesOverlayProvider.test.tsx
src/components/shared/ReactFlow/NodesOverlay/NodesOverlayProvider.tsx
src/hooks/useNodeCallbacks.ts
src/providers/ComponentLibraryProvider/libraries/publishedComponentsLibrary.ts
src/utils/componentStore.ts

Added functionality to detect and upgrade published components within the pipeline. This PR introduces a new UI for displaying published component details, checking for updates, and upgrading tasks to newer component versions.
Key changes:
- Added a published component badge to task nodes
- Created a component details panel showing published status and version information
- Implemented a force update mechanism to upgrade tasks using outdated components
- Added a dialog context to manage component detail dialogs
- Created a popover UI for upgrading nodes with confirmation workflow
https://github.com/user-attachments/assets/4dd23b11-6bdb-4090-ba3f-47f930de5d8b
1. Enable the "remote-component-library-search" beta flag
2. Create a task using a published component
3. Verify the published …

upgrade path for published components

---

src/components/Editor/PipelineEditor.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/FileActions.tsx
src/providers/AutoSaveProvider.tsx
src/providers/ComponentSpecProvider.tsx

Moves Autosave out of ComponentSpec Provider and into its own AutoSaveProvider.
This means we can now pull autosave state without updating the entire ComponentSpecProvider and all of its consumers.
App should continue to work as previously.
Looking at ComponentSpecProvider I may (separately) also do a similar thing for `undoRedo`

Add AutoSaveProvider

---

src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/SuspenseWrapper.tsx

Enhanced the `ComponentIcon` component with a skeleton fallback and added conditional rendering based on a beta flag. The changes include:
1. Created a `ComponentIconSkeleton` component to serve as a fallback during loading
2. Improved the `withSuspenseWrapper` function to pass props to the Skeleton component
3. Added conditional rendering for component icons based on the `remote-component-library-search` beta flag
1. Enable the `remote-component-library-search` beta flag to see the ComponentIcon with outdated component detection
2. Disable the flag to see the standard icon behavior
3. Verify that the skeleton appears correctly during loading states

fix ComponentItemIcon to be used behind the betaflag only

---

src/components/shared/ManageComponent/PublishedComponentBadge.tsx
src/components/shared/SuspenseWrapper.tsx

Enhanced the error handling in `PublishedComponentBadge` by adding a custom error fallback that displays the component's children when an error occurs. This improves the user experience by showing partial content instead of a complete error state.
The `withSuspenseWrapper` function has been updated to pass the original component props to error fallbacks, allowing for more contextual error handling. This enables components to gracefully degrade by showing partial content when errors occur rather than completely failing.

fix published component node card badge error message

---

src/components/Editor/InputValueEditor/FormFields/FormFields.tsx
src/components/Editor/InputValueEditor/InputValueEditor.tsx
src/components/Editor/PipelineDetails.tsx
src/components/shared/ReactFlow/FlowCanvas/IONode/IONode.tsx
src/components/ui/icon.tsx

Converts InputValueEditor into a save-on-blur component to align it with the rest of the patterns used elsewhere in the app and hook it into the autosave system.
Removes the "Save" button; fields will now save automatically when blurred. Renamed "Cancel" to "Close"
Progresses https://github.com/Shopify/oasis-frontend/issues/239

InputNode Save-on-Blur

---

src/components/shared/ReactFlow/FlowCanvas/IONode/IONode.tsx
src/components/shared/ReactFlow/FlowCanvas/utils/getOutputConnectedDetails.ts

Fixes a bug with IO Nodes where the node would always display "Type: Any" when not connected, even if the user entered a type in the box.
Also amends a few TypeScript Types in related methods.

Fix Unconnected IO Nodes only have type: Any

---

src/components/Editor/IOEditor/InputValueEditor/FormFields/FormFields.tsx
src/components/Editor/IOEditor/InputValueEditor/InputValueEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/hooks/useIOSelectionPersistence.test.ts
src/hooks/useIOSelectionPersistence.ts

Fixes an issue where IO Node Context Panel gets out of sync when using Undo-Redo with the panel open. This was occurring due to stale node selection state.
This PR works by comparing ComponentSpec changes on each ReactFlow render and looking for IO Node replacements. It then tries to preserve the selection state across that replacement. 
Progresses https://github.com/Shopify/oasis-frontend/issues/243
1. Create an input or output node
2. rename it
3. make sure the context panel for the node is still open
4. undo the rename action using the undo button or ctrl + z
5. the node should rename and stay selected and the panel should update accordingly
6. now redo the rename action and see if everything updates again as expected
The implemented solution is largely AI-generated and is not ideal. …

Fix IO Node Desync on Undo-Redo

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx

Added the task ID display in the TaskNodeCard component when it differs from the node name and doesn't follow the pattern of "name + number". This helps users identify tasks with custom IDs that differ from their display names.
1. Create a task with a custom ID that differs from its name or open an existing run e.g. [01993cf05ac24c9d3e90](https://oasis.shopify.io/runs/01993cf05ac24c9d3e90) (change the host to the localhost or staging)
2. Verify that the ID appears below the task name in the node card
3. Verify that IDs that match the pattern "name + number" are not displayed
4. Verify that IDs identical to the name are not displayed

Added task name to the component card

---

src/components/Home/RunSection/RunSection.tsx
src/components/PipelineRun/RootExecutionStatusProvider.test.tsx
src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/components/CancelPipelineRunButton.test.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/tests/logs.test.tsx
src/providers/BackendProvider.tsx
src/routes/PipelineRun/PipelineRun.tsx
src/services/executionService.ts
src/utils/fetchWithErrorHandling.ts

Adds logic for improved error reporting on Pipeline Run `fetch` requests via a new `fetchWithErrorHandling` method. Also reworks some logic to minimize the amount of requests made when the backend is not available, and improves backend loading logic to prevent unnecessary "backend unavailable" errors appearing while it is loading.
Also removes a few redundant backend-triggered refetches, as the refetch is done automatically by a changing `queryKey`
Additionally, backend availability issues in the above scenarios are now reported separately to network/fetch issues.
Prompted by multiple user reports of unhelpful error messages when loading/viewing runs.
Tangentially related to https://github.com/Shopify/oasis-frontend/issues/217 but not directly addressing.
1. mock some bad requests and try …

Improved Fetch/Backend Error Reporting

---

src/favicon.ts
src/routes/PipelineRun/PipelineRun.tsx

favicon will now update to match run status in that tab.
Icon will revert to default if not on a run route.
Icons will only update if the tab is open -- I will explore streaming/realtime updates separately.
Closes https://github.com/Shopify/oasis-frontend/issues/253
Running pipeline (left), old icon (right)
Failed pipeline

Change favicon to match PipelineRun status

---

src/components/ui/radiogroup.tsx

Height was not applying to the `Icon` component. We may want to investigate that component further since it seems to be struggling to apply all inherent styling.
"selected" dot is now back inside the circle
Closes https://github.com/Shopify/oasis-frontend/issues/267

Fix Radio Button misplaced circle

---

src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/RunDetails.tsx
src/hooks/useLoadComponentSpecFromPath.ts

Hides the "Inspect Pipeline" button from the run details if the user does not have the associated pipeline stored in local storage (i.e. if they do not have access to the editor route for that pipeline).
Noted by @Zruty0 in Slack.
1. Create a pipeline
2. Run the pipeline
3. Inspect button should be present on the run
4. Go to pipeline list & delete the pipeline
5. Revisit the run
6. Inspect button should no longer be visible

Hide Inspect Button if Pipeline does not exist in Storage

---

src/components/PipelineRun/RunDetails.test.tsx
src/components/PipelineRun/RunDetails.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/hooks/useCheckComponentSpecFromPath.ts
src/hooks/useLoadComponentSpecFromPath.ts
src/routes/Editor/Editor.tsx
src/routes/PipelineRun/PipelineRun.test.tsx

Resolves an issue introduced in #970 that resulted in a Run's editor version of the component spec being loaded. This resulted in tasks on the runs having missing (or outdated) execution ids and thus missing (or outdated) artifacts and logs.
This PR resolves that by separating out the `check if spec exists` use case from the original `load the spec` use case. In particular, the issue was caused by `setComponentSpec` being trigged when a url was checked.
Adds tests to the PipelineRun Route to check that tasks have execution ids attached to them.
**Original Issue**
In PR #970 `useLoadComponentSpecFromPath` is being used to test a url and see if the editor route from a pipeline can be loaded. I added some escape hatches to the hook for this scenario to avoid any permanent state changes but …

Resolve Issues with useLoadComponentSpecFromPath making permanent changes when checking a url

---

src/utils/submitPipeline.test.ts
src/utils/submitPipeline.ts

Fixes a bug introduced in #746 that resulted in pipelines runs being saved with the incorrect pipeline name, resulting in the pipeline having the inability to fetch them back again.
Fixes some of the items in https://github.com/Shopify/oasis-frontend/issues/284

Fix Bug in Run Submission
