Cloud-Pipelines/pipeline-studio-app

package-lock.json
package.json
src/App.test.tsx
src/App.tsx
src/DragNDrop/ArgumentsEditor.tsx
src/components/PipelineCard.tsx
src/components/ui/alert.tsx
src/components/ui/select.tsx
src/index.tsx
src/routes/Editor.tsx
src/routes/Home.tsx
vite.config.js

This PR adds the basic structure for a home page populated with saved experiments and their associated runs (currently dummy data).

This PR adds a new home page route and populates it with saved pipelines

---

src/DragNDrop/PipelineLibrary.tsx
src/DragNDrop/Sidebar.tsx
src/DragNDrop/index.tsx
src/components/EditorMenu.tsx
src/components/NewExperiment.tsx
src/components/PipelineCard.tsx
src/routes/Home.tsx
src/utils/loadPipelineByName.ts
src/utils/prepareComponentRefForEditor.ts

This PR removes the localstorage auto save in favour of a URL based loading mechanism.

Load pipelines by URL

---

package-lock.json
package.json
src/DragNDrop/ComponentTaskNode.tsx
src/DragNDrop/PipelineLibrary.tsx
src/DragNDrop/PipelineSubmitter.tsx
src/DragNDrop/ShopifyCloud.tsx
src/DragNDrop/index.tsx
src/components/NewExperiment.tsx
src/components/PipelineCard.tsx
src/components/RunCard.tsx
src/components/ui/tooltip.tsx
src/router.tsx
src/routes/Home.tsx
src/routes/RunDetails.tsx
src/routes/Runs.tsx
src/utils/constants.ts
src/utils/mockAPI.ts

This PR adds runs view and logic

Adds run logic and views

---

src/DragNDrop/ShopifyCloud.tsx
src/DragNDrop/index.tsx
src/routes/RunDetails.tsx
src/utils/loadPipelineByName.ts
vite.config.js

This PR adds a base to our vite config, changes where the user is re-directed to when submitting a pipeline, and some UI cleanup

Fixes graph layout and submit pipeline button

---

src/DragNDrop/ShopifyCloud.tsx
src/cacheUtils.ts
src/routes/RunDetails.tsx

This PR adds a refetchInterval of 5 seconds so our runs status will update.

On the pipelineDetails page we shoudl pull every 5 seconds

---

src/components/AppFooter.tsx

Fixes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/71

feat: Show app version (Git SHA) in the app footer

---

index.html

Fixes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/74

Added crossorigin="use-credentials" to manifest.json

---

src/DragNDrop/DraggableComponent.tsx
src/components/PipelineRow/RunListItem.tsx
src/components/PipelineRow/index.tsx
src/routes/Home.tsx

Display name of run and fixes design for draggable components from sidebar

---

src/components/AppFooter.tsx
src/components/AppMenu.tsx
src/components/ImportPipeline.tsx
src/utils/copyRunToPipeline.ts
src/utils/importPipeline.test.ts
src/utils/importPipeline.ts

This PR adds an import pipeline button to the header so our users can either upload or paste pipelines. This PR also runs linting

Add import pipeline to header

---

package-lock.json
package.json
src/DragNDrop/ArgumentsEditor.tsx
src/DragNDrop/ArgumentsEditorDialog.tsx
src/DragNDrop/ComponentTaskNode.tsx
src/components/ExecutionDetailsSheet.tsx
src/components/ui/sheet.tsx

This PR adds
- Settings button on each PIPELINE task that opens up the argument dialog instead of a double click
- Information icon on each RUN task node that opens up a "Sheet" to the side
- The sheet has tabs for information, I/O, logs, and more if needed
- We are only populating the I/O for this PR

Adds a drawer and I/O for a run task.

---

src/routes/Home.tsx

Addresses items 1 and 2 in https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/105
The remaining issues could not yet be addressed due to a CORS issue block run execution.

Make 'Runs' the default tab and move Alert into 'Pipelines'

---

src/DragNDrop/ShopifyCloud.tsx

Disable 'Submit Run' button if there is no graph

---

src/routes/Home.tsx

If a next / previous page token exists we enable the next or previous button and fetch the next batch of runs

Adds pagination to the home page runs

---

.env.example
src/components/AppFooter.tsx
src/utils/constants.ts

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/106
Values will fallback to the current cloud-pipelines values if the environment variables are left blank.

Allow configuration of footer links via environment variables

---

src/components/TaskDetailsSheet/artifacts.tsx
src/components/TaskDetailsSheet/index.tsx
src/routes/RunDetails.tsx

This PR uses the artifact by child_task_execution_ids

Adds Artifacts for each task in a run

---

src/DragNDrop/DraggableComponent.tsx
src/components/CondensedUrl.tsx
src/components/TaskDetailsSheet/artifacts.tsx
src/components/TaskDetailsSheet/index.tsx
src/components/TaskDetailsSheet/info.tsx

Follow up to  https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/118

Componentize URLs

---

src/components/PipelineRow/StatusText.tsx

Quick fix to trailing commas on StatusText

---

src/components/PipelineSection/PipelineSection.tsx

This PR adds the ability to search for pipelines by name

Adds search pipelines by name

---

src/components/PipelineRow/index.tsx
src/components/PipelineRow/types.ts
src/components/PipelineSection/PipelineSection.tsx

Pipelines are now sorted by last updated instead of alphabetical. I've also added a modified at column

Pipelines are now ordered by last updated

---

src/appSettings.ts
src/github.ts

Closes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/107

Disable GitHub Search

---

src/DragNDrop/ShopifyCloud.tsx

When you click submit run, we now disable the button for 3 seconds until you can submit again. I've also added a timer showing the 3 second countdown.

Adds a 3 second timeout for submit run button

---

src/components/PipelineRow/index.tsx
src/components/PipelineRow/types.ts
src/components/PipelineSection/PipelineSection.tsx

In an effort to clean up our code and UI, I have created a hook to fetch pipeline data, which we will be using in our table on the home page. I have also added some additional information to each row and generally cleaned up the UI
Before
After

Updates and cleans up pipeline row components

---

src/components/FlowSidebar/components/ComponentItem.tsx
src/components/FlowSidebar/components/FolderItem.tsx
src/components/FlowSidebar/components/LibraryStates.tsx
src/components/FlowSidebar/components/SearchInput.tsx
src/components/FlowSidebar/components/index.ts
src/components/FlowSidebar/sections/GraphComponents.tsx
src/components/FlowSidebar/sections/SettingsAndActions.tsx
src/components/ImportPipeline.tsx
src/services/componentSpecService.ts
src/types/componentLibrary.ts
src/utils/searchUtils.test.ts
src/utils/searchUtils.ts

This PR introduces a comprehensive component library for the Oasis app, making it easier to browse, search, and import components into your pipelines.
- **Component Browsing**: Hierarchical folder structure for better organization
- **Component Metadata Display**: View component name, description, inputs, and outputs
- **Search Functionality**: Filter components by name, description, inputs, outputs, or URL
- **Drag and Drop Integration**: Seamlessly drag components onto the flow canvas
- **Rich Tooltips**: Hover over components to see detailed information
- Added a modular architecture for the component library with separate components for:
- Component items (`ComponentItem.tsx`)
- Folders with collapsible UI (`FolderItem.tsx`) 
- Search input with real-time filtering
- Loading, error, …

Adds components to side bar

---

src/components/PipelineRow/PipelineRow.tsx
src/components/PipelineRow/types.ts
src/components/PipelineSection/PipelineSection.tsx
src/utils/deletePipeline.ts

Adds a button to the PipelineRow that allows a pipeline to be deleted.
This won't impact existing runs on that pipeline.

Add Button to Delete Pipelines

---

src/components/shared/ReactFlow/FlowGraph/TaskNode/TaskDetailsSheet/info.tsx

Fixes https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/127

chore: Execution details - Show task spec as YAML

---

package-lock.json
package.json
src/components/Home/RunSection/RunSection.tsx
src/components/ui/switch.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/68
This PR adds a "switch" component that allows us to filter by `me`. If using this on local, all runs will return because "me" is `unknown`.

Add filter by me toggle

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskDetailsSheet/logs.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/72
This PR  cleans up the logs component as well as refreshes them every second as long as the window is focused and the component is rendered.
- I have moved the loading and no logs functionally to the data fetching layer and removed redundant code. 
- If the component is fetching AND there are no logs we render the loading state
- If the component has logs display them
- if the component is refetching but has logs from previous fetch display the old logs until the new ones come in
- if the component is fetching for the first time and has an error display the error
- if the component is refetching, had data, but errors on the 2nd fetch display the logs

Refreshes logs every second

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/Status/StatusIcon.tsx

Not all of the states were covered, so this PR addresses that by adding the new states and fixes colouring.

Adds new states for runs

---

src/routes/PipelineRun/PipelineRun.tsx

We previously removed this when updating the status of the run tasks. I've updated it so we ignore the status and just add the executionId

This re-adds logic to add executionId to component spec

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/TaskDetails/Details.tsx
src/utils/yaml.ts

fix bug where toolbar appears when selecting multiple nodes in run view

hide selection toolbar from run view

---

src/components/shared/Dialogs/ComponentDetailsDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ComponentItem.tsx
src/components/shared/ReactFlow/FlowSidebar/components/UserComponentItem.tsx
src/components/shared/TaskDetails/Details.tsx

I've updated the user component to have a delete button that is similar to the delete node button. I have also added the digest number below existing components so we know the version.
https://github.com/user-attachments/assets/cbcdb370-48b8-4021-9567-3d2331487d45

Delete user component

---

src/components/shared/CloneRunButton.tsx
src/components/shared/Dialogs/DraggableDialog.tsx
src/components/shared/Dialogs/NewExperimentDialog.tsx
src/components/shared/Dialogs/PipelineNameDialog.tsx
src/components/shared/ImportPipeline.tsx
src/components/shared/OasisSubmitter.tsx
src/components/shared/ReactFlow/FlowCanvas/SelectionToolbar.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsEditorDialog.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentsSection.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ImportComponent.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx
src/components/shared/TaskDetails/Details.tsx

It's baked into the base Button class now.

Remove unnecessary instances of cursor-pointer

---

src/components/Editor/PipelineEditor.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/components/shared/ReactFlow/FlowCanvas/Edges/SmoothEdge.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx
src/hooks/useComponentSpecToEdges.test.ts
src/hooks/useComponentSpecToEdges.ts
src/services/componentService.ts
src/utils/string.ts

This PR updates the design of the task nodes as well as cleans up some of the task nodes logic to make it easier to understand.
Before:
After: (note I show the updating of a node to show it still works.)
https://github.com/user-attachments/assets/7275fa36-d493-46ea-b39f-1fb138eac1d6
Long names will get truncated

New task nodes

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

The new zoom values:
minZoom 0.5 => 0.01
maxZoom= 2 => 3

Add new zoom values

---

src/components/shared/OasisSubmitter.tsx

When we submit a subgraph, we are required to preload the component spec. This PR adds that functionality

Preload component references

---

src/components/shared/ReactFlow/FlowSidebar/components/ImportComponent.tsx

The drop zone of the import component is much larger now.

Make the import component drop zone bigger

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/io.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/ioCell.tsx

I've update the arguments UI to make it feel a little cleaner

The artifacts and IO ui has been updated

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/ioCell.tsx
src/components/ui/tooltip.tsx
src/utils/string.ts

This PR lets our user click the name of an artifact to copy it instead of having to highlight it to copy it.
https://github.com/user-attachments/assets/6a2db146-752b-4803-9c62-4b835dade8ac

Allow our users to copy the name of an I/O on click

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/StatusIndicator.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNode.tsx

Move supporting methods & components out into their own files.
No changes to app functionality.

Reorganize TaskNode.tsx

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfigurationSheet/TaskConfigurationSheet.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/92

Rename inputs/outputs to arguments

---

src/components/PipelineRun/PipelineRunPage.tsx

This PR fixes an issue where we require a component library provider on the runs page

Adds componentLibraryProvider to runs page

---

src/components/shared/CodeViewer.tsx

A small workaround/hack to resolve a pain-point: the fullscreen code viewer _feels_ like a new page (but isn't). This PR does a little bit of browser manipulation so that when the Browser Back button is pressed it will exist fullscreen mode.
We should consider using a modal route in future to manage this functionality, as it will be cleaner on the browser history. (this current solution should not be permanent as history manipulation can be a contentious topic)

Close fullscreen codeviewer on Back

---

.github/PULL_REQUEST_TEMPLATE.md

This PR updates the name of `User components` to `My components` as well as adds this PR template as a default.
N/A
This template can be iterated on as we grow.

Adds PR template and updates user compoentns name

---

src/components/shared/CodeViewer.tsx

Adds a vertical scrollbar to the code viewer when needed in fullscreen mode. As requested on Slack.
n/a
n/a
n/a

Add vertical scrollbar to fullscreen codeviewer

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeOutputs.tsx
src/providers/ComponentLibraryProvider.tsx
src/utils/constants.ts

Fixes a couple of bugs:
- Incorrect search filter applied when clicking a Handle
- No default filter applied when typing in the search bar
- Infinite render caused by I/O handles
- Flickering Handle Highlights when dragging an edge
Bugfixes for #315 and other related PRs.
n/a
bug fixes

Bugfix Component Search and Node Handles

---

.github/PULL_REQUEST_TEMPLATE.md

Add the change field "Improvement"; for items that improve upon an existing feature.
n/a
Improvement.
n/a
n/a

Update Git Template

---

src/components/shared/OasisSubmitter.tsx
src/components/shared/ReactFlow/FlowSidebar/FlowSidebar.tsx
src/components/shared/ReactFlow/FlowSidebar/components/ImportComponent.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/GraphComponents.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/RunsAndSubmission.tsx
src/components/shared/ReactFlow/FlowSidebar/sections/SettingsAndActions.tsx
src/components/ui/sidebar.tsx

This pull request introduces several enhancements to the sidebar components in the React Flow library, focusing on improving usability, adding collapsible behavior, and refining tooltip functionality. The changes primarily involve updates to the `FlowSidebar` and its subcomponents, along with modifications to the `SidebarMenuButton` and `SidebarGroupLabel` to support dynamic tooltips and collapsible states.
* **Collapsible Sidebar**: Added state management (`isOpen`) to the `FlowSidebar` component, enabling collapsible behavior. This includes dynamic positioning for the `SidebarTrigger` and conditional rendering of sidebar content based on the open state. (`[src/components/shared/ReactFlow/FlowSidebar/FlowSidebar.tsxL1-R41](diffhunk://#diff-91adbb0939bc922091d9f80c2eaf8b6cc875875d2c37cb6cf …

Make sidebar collapsible

---

src/components/ui/sidebar.tsx

removes a console log

---

package.json

See: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/421

fix: Build - Fixed base URL for GitHub pages

---

.vscode/settings.json

Run prettier on save. Depends on recommended plugin https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
I noticed, that VSCode skips formatting on save.
No impact on application

Run code formatting on file save

---

public/component_library.yaml

* Added many components that work with Apache Parquet dataset format (data manipulation, training, prediction, conversion).
* Added converter components for different dataset formats and ML model formats.
* Updated some components to latest versions.
* Added: 23, Updated: 2

feat: Big update for the Component Library

---

src/components/Home/RunSection/RunRow.tsx

Can now click on the `initiated by` field in the runs list to copy the user email address.
Long email addresses (> 28 characters) will be truncated in the middle. Truncated names will have a tooltip to show the full string.
Closes https://github.com/Shopify/oasis-frontend/issues/132

Run created_by field is now copiable and will truncate long strings

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeOutputs.tsx

Moves task node click from [IO nodes PR](https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/424/files) to here
We are now defaulting to arguments when anything on a task node is clicked.
copilot:
This pull request simplifies the `TaskNode` components in the `ReactFlow` flow canvas by removing unused props and redundant callbacks, streamlining the codebase for better maintainability and readability. The most significant changes include the removal of the `focusedIo` state and associated logic, as well as unused event handlers like `handleIOClicked`.
* [`src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx`](diffhunk://#diff-4348f37088bf0541544ff44ada9198fe06bd156e03b80be9094916fc29f7690dL36-R38): Removed the `focusedIo` prop from …

Default task arguments on node click

---

src/components/Editor/PipelineDetails.tsx
src/components/Editor/PipelineEditor.tsx
src/components/PipelineRun/PipelineRunPage.tsx
src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeCard.tsx
src/providers/ContextPanelProvider.tsx
src/utils/flowUtils.ts

This PR pulls in changes from my[ IO node PR](https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/424).
The contextPanelProvider now has 3 arguments: ` content`, `setContent`,`clearContent`. As well as adds an event listener for when a user hits escape. 
If a user hits escape we will clear all of the nodes that are selected as well as calls clearContent, which now sets the contextpanel to its default state.
COPILOT:
This pull request introduces several updates to improve the user experience and functionality of the pipeline editor, pipeline run page, and context panel. The changes include adding a loading spinner, enhancing the behavior of the context panel, and simplifying its API. Additionally, a utility function for deselecting nodes in the flow canvas has been added.
* Added a …

Makes contextPanelProvider a little more simple

---

Dockerfile
nginx.conf

- [] New feature
- [x ] Improvement

chore: Added Dockerfile and nginx.conf

---

src/components/Editor/PipelineDetails.tsx
src/components/Editor/PipelineEditor.tsx
src/components/Editor/RenamePipeline.tsx

closes: https://github.com/Shopify/oasis-frontend/issues/158
There was an issue where the sidebar was not updating/receiving the correct component spec after a user updated the title. This fixes that
COPILOT:
This pull request refactors the `PipelineDetails` and `RenamePipeline` components to simplify their props and rely on the `useComponentSpec` hook for accessing the `componentSpec` context. The changes improve maintainability by centralizing the state management of `componentSpec`.
* [`src/components/Editor/PipelineDetails.tsx`](diffhunk://#diff-3b726b146de91fa0b684dc3c8afa4415c7aa311812f0043a8e5218e148376f15L6-R17): Removed the `PipelineDetailsProps` type and updated the `PipelineDetails` component to use the `useComponentSpec` hook instead of receiving `componentSpec` as a prop. …

Fix: Renaming PipelineDetails now shows the change on the side bar immediately

---

src/components/shared/GitHubAuth/useGitHubAuthPopup.ts

Fixes: https://github.com/Shopify/oasis-frontend/issues/163

fix: Fixed the URL construction bug

---

public/component_library.yaml

See https://github.com/Ark-kun/pipeline_components/commit/e78420c1594aca49605a816f4fd696466b641aac

chore: Component Library - Fixed all preloaded library components that use Pandas

---

src/components/shared/InfoBox.tsx
src/components/shared/Submitters/GoogleCloud/ManualSubmissionInstructions.tsx

Does a simple refactor to componentize into an info box that can be reused in #527

Add InfoBox Component

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Simple UX improvement requested a long time ago by @Zruty0 
Shift+Delete to skip the confirmation dialog when deleting selected nodes.

Shift+Delete to Skip Confirmation

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/io.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/logs.tsx
src/utils/backend.ts

Follows the approved format established in #551 to integrate the new configurable backend functionality into task execution logs and artifacts
A continuation from #551 & progresses https://github.com/Shopify/oasis-frontend/issues/133
Go to an executed pipeline and use the backend configuration dialog to explore how Artifacts and Logs accessibility changes depending on how the backend is configured.
Pipeline executions and runs will come in a follow-up PR

Integrate Configurable Backend into Execution Logs and Artifacts

---

src/hooks/useLoadComponentSpecFromPath.ts
src/services/executionService.ts

Fix Pipeline Run page issues & infinite backend calls

Fix ComponentSpec Loading Issues & Backend Spam

---

src/hooks/useRequiredContext.ts
src/providers/BackendProvider.tsx
src/providers/ComponentLibraryProvider.tsx
src/providers/ComponentSpecProvider.tsx
src/providers/ContextPanelProvider.tsx
src/providers/PipelineRunsProvider.tsx
src/providers/TaskNodeProvider.tsx

Add `useRequiredContext` to simplify the structure of our providers.
Based on this comment: https://github.com/Cloud-Pipelines/pipeline-studio-app/pull/455#discussion_r2183324349
No change to app functionality

Add useRequiredContext

---

src/components/Editor/PipelineEditor.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsSection.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/ArgumentsEditor/ArgumentInputField.tsx
src/components/shared/UndoRedo.tsx
src/hooks/useAutoSave.ts
src/hooks/useDebouncedState.ts
src/hooks/useHistoryManager.ts
src/hooks/useUndoRedo.ts
src/providers/ComponentSpecProvider.tsx
src/utils/constants.ts
src/utils/prepareComponentRefForEditor.ts

Adds undo + redo functionality to the Pipeline Editor.
This is achieved through a new hook `useUndoRedo`, an `UndoRedo` component and some updates to componentSpecProvider and `useAutoSave`.
`useUndoRedo` will keep a stack of changes to the componentSpec, debounced every 500ms and up to 50 entries. `UndoRedo` adds interactive buttons on the bottom right of the canvas, as well as the typical keyboard shortcuts `cmd+Z` and `cmd+Y`.
The undo stack allows for branching off at any point, at which the previous redo stack will be overwritten with new edits, as per normal undo-redo behaviour. Any update to the componentSpec is a valid change, including: position, annotations, arguments, new tasks, and so on.
The history stack will be lost upon reload of the componentspec; it is not saved to local …

Add Undo-Redo to Pipeline Editor

---

src/components/shared/ReactFlow/FlowCanvas/FlowCanvas.tsx

Closes https://github.com/Shopify/oasis-frontend/issues/175
1. Open any pipeline.
2. Observe it automatically fits view so the entire pipeline is visible.
https://github.com/user-attachments/assets/666116d7-ab51-4379-81b2-1abb2055108a

fit view on pipeline load

---

src/components/layout/AppMenu.tsx
src/components/layout/RootLayout.tsx
src/components/shared/CloneRunButton.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/ioCell.tsx
src/hooks/useLoadComponentSpecFromPath.ts
src/providers/ComponentSpecProvider.tsx
src/routes/Editor/Editor.tsx
src/routes/PipelineRun/PipelineRun.tsx

Partly resolves: https://github.com/Shopify/oasis-frontend/issues/171
Resolves: https://github.com/Shopify/oasis-frontend/issues/204
This pull request refactors how the `ComponentSpec` state is managed throughout the app, centralizing its handling in the `ComponentSpecProvider` and updating hooks and components to use context instead of local state. This change simplifies state management, prevents redundant providers, and improves cleanup of component specs. The most important changes are grouped below.
**Centralization and Cleanup of ComponentSpec State:**
* The `ComponentSpecProvider` now manages all `componentSpec` state, exposing new methods like `clearComponentSpec` for proper cleanup, and removing local state from hooks and components. …

Cleans up componentSpecProvider

---

src/components/shared/ExecutionDetails/ExecutionDetails.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskConfiguration/TaskConfiguration.tsx
src/components/shared/TaskDetails/Details.tsx
src/services/executionService.ts
src/utils/constants.ts
src/utils/date.test.ts
src/utils/date.ts

closes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/154
This pull request enhances the task execution details shown in the UI by introducing richer container execution state information, improving type safety for task status tracking, and adding utility functions for formatting durations. The changes affect how task statuses and execution metadata are managed and displayed, providing users with more actionable insights into pipeline runs.
**Task Execution State Enhancements:**
- The `TaskDetails` component now fetches and displays detailed container execution state information, including execution ID, exit code (with Out of Memory detection), start/completion times, and execution duration. This is shown in a new "Execution Details" collapsible section. …

Add Execution Details to task node details

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/handleUtils.test.ts
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/handleUtils.ts

closes: https://github.com/Cloud-Pipelines/pipeline-studio-app/issues/294
This pull request enhances how input values are displayed in task node handles, making it clearer when a value is connected to another node versus being a literal value. It introduces a new utility function for formatting these values, updates the UI to leverage tooltips for better readability, and provides thorough test coverage for the new logic.
**Display improvements for input handle values:**
* Added a new `getDisplayValue` utility in `handleUtils.ts` to format input values, showing connected nodes as `→ ComponentName.outputName` and formatting other values for readability. (`src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/handleUtils.ts`, …

Show connection value instead of json on task node

---

src/components/Home/RunSection/RunSection.tsx

EDIT: I am putting this in WIP because we don't have a way, from a link, to paginate back to the previous page.
This pull request refactors the `RunSection` component to use URL query parameters for managing pagination and filtering, improving browser navigation and shareability of state. The main changes involve replacing local state with URL-based state and updating navigation logic accordingly.
**Routing and State Management Improvements:**
* Replaced local state (`useCreatedByMe` and `pageToken`) with values derived from the URL's search parameters, making the filter and pagination state part of the browser's address bar and shareable/bookmarkable.
* Updated the handlers for filter changes and pagination (`handleFilterChange`, `handleNextPage`, `handlePreviousPage`) to update the URL …

Filters work with url params instead of state

---

src/components/shared/ExecutionDetails/ExecutionDetails.tsx

Show the execution podname in the UI for debugging purposes, if available.
Closes https://github.com/Shopify/oasis-frontend/issues/200

Add Pod name to Execution Details if Available

---

src/components/shared/Status/StatusIcon.tsx

Amusingly our spinner was point anticlockwise but spinning clockwise, making it spin backwards. This PR makes it point clockwise so that it now spins in a forward direction.
(previously)

Running Status Spinner now points in the correct direction

---

src/components/PipelineRun/RunDetails.test.tsx
src/components/shared/Buttons/InfoIconButton.tsx
src/components/shared/FavoriteStar.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/Handles.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/TaskNodeCard/TaskNodeInputs.test.tsx
src/components/shared/ReactFlow/FlowSidebar/components/SearchFilter.tsx
src/components/shared/ReactFlow/FlowSidebar/components/SearchInput.tsx
src/components/shared/ReactFlow/FlowSidebar/components/SearchResults.tsx
src/providers/ComponentLibraryProvider/ComponentLibraryProvider.test.tsx
src/providers/ComponentLibraryProvider/ComponentLibraryProvider.tsx
src/providers/ComponentLibraryProvider/componentLibrary.test.ts
src/providers/ComponentLibraryProvider/componentLibrary.ts
src/providers/ComponentLibraryProvider/index.ts
tests/e2e/componentlib.spec.ts
tests/e2e/flowcanvas.spec.ts
tests/e2e/helpers.ts

This PR adds comprehensive test coverage for the component library and flow canvas functionality. It includes new unit tests for the ComponentLibraryProvider, task node inputs validation, and improves existing tests by using React Testing Library's `act` function to properly handle asynchronous rendering. The PR also adds data-testid attributes to various components to facilitate testing and adds end-to-end tests for component library interactions.
1. Run the unit tests to verify the new test coverage for ComponentLibraryProvider and task node inputs
2. Run the e2e tests to verify component library interactions work as expected
3. Verify that the RunDetails tests still pass with the updated testing approach
The PR adds two new e2e test files:
- `componentlib.spec.ts` - Tests component …

prepare lib refactoring improve tests

---

src/components/shared/CodeViewer/CodeSyntaxHighlighter.test.tsx
src/components/shared/CodeViewer/CodeSyntaxHighlighter.tsx
src/components/shared/CodeViewer/CodeViewer.tsx
src/components/shared/TaskDetails/Implementation.tsx

Fixes an issue where the Monaco Editor would not update when components are added to the canvas
Closes https://github.com/Shopify/oasis-frontend/issues/219

Fix Monaco Editor out of sync

---

src/components/shared/CodeViewer/CodeSyntaxHighlighter.test.tsx
src/components/shared/CodeViewer/CodeSyntaxHighlighter.tsx

Fixes an error introduced by #789 
Closes https://github.com/Shopify/oasis-frontend/issues/224

Fix async Error with MonacoEditor

---

src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsInput.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/AnnotationsSection.tsx
src/components/shared/ReactFlow/FlowCanvas/TaskNode/AnnotationsEditor/ComputeResourcesEditor.tsx

Updates Annotation Editor components to wrap all methods in `useCallback`
No change to app functionality.

Add Annotations Editor UseCallbacks

---

package-lock.json
package.json
src/components/shared/ReactFlow/FlowSidebar/components/PublishedComponentsSearch.tsx
src/components/ui/input.tsx
src/components/ui/radiogroup.tsx

Added a radio group component and improved the search filter UI in the FlowSidebar. The changes replace checkboxes with radio buttons for search filters, allowing users to select only one filter at a time. Also added scrolling functionality to search results to better handle large result sets.
[Screen Recording 2025-09-05 at 12.28.47 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/3b104921-8dbc-42e7-820c-8690abcd2800.mov" />](https://app.graphite.dev/user-attachments/video/3b104921-8dbc-42e7-820c-8690abcd2800.mov)
1. Added `@radix-ui/react-radio-group` dependency
2. Created a new `radiogroup.tsx` component with RadioGroup and RadioGroupItem
3. Updated PublishedComponentsSearch to: …

improve remote search ux

---

src/components/shared/Dialogs/PipelineNameDialog.tsx

Tidy up, add `useCallback` and move onto UI Primitives

Cleanup PipelineNameDialog

---

src/components/shared/Dialogs/ComponentDuplicateDialog.tsx
src/components/shared/InfoBox.tsx
src/components/ui/input.tsx
src/styles/global.css

Tidy up, add `useCallback` and move onto UI Primitives
Note: I added a new `info` global colour but then didn't end up using it. I decided to leave it in as we can transition to it across the app later.

Cleanup ComponentDuplicateDialog

---

src/components/shared/Dialogs/BackendConfigurationDialog.tsx
src/components/ui/typography.tsx

Tidy up, add `useCallback` and move onto UI Primitives

Cleanup BackendConfigurationDialog

---

src/components/shared/ReactFlow/FlowCanvas/IONode/IONode.tsx
src/components/ui/typography.tsx

better logic and move to UI primitives

Cleanup IONode.tsx

---

src/components/shared/Dialogs/MultilineTextInputDialog.tsx

Multiline Text Editor will now increase in height to a limit and stay on the screen rather than expand infinitely off-screen. Thus, it is also scrollable.
User-reported.

Max Height on Multiline Editor

---

src/components/Home/PipelineSection/PipelineRow.tsx
src/components/Home/PipelineSection/PipelineRow/index.ts
src/components/Home/PipelineSection/PipelineSection.tsx

Bring onto our UI primitives and add missing useCallbacks etc. Deleted the `PipelineRow` directory as it was not really serving any purpose. `PipelineRow.tsx` now lives in `PipelineSection`.
No change to app functionality.

Cleanup PipelineSection

---

src/components/Editor/IOEditor/InputValueEditor/InputValueEditor.tsx
src/components/Editor/IOEditor/OutputNameEditor/OutputNameEditor.tsx

Trim IO Node Names & fix a bug where they could be blank. A validation error will now show.

IO Node Names cannot be blank

---

src/components/PipelineRun/RunDetails.tsx
src/components/PipelineRun/components/InspectPipelineButton.tsx
src/components/shared/Dialogs/PipelineNameDialog.tsx
src/hooks/useCheckComponentSpecFromPath.ts
src/utils/constants.ts

Remove restrictions on special characters in pipeline naming. Special characters will encode correctly in urls. Also trimmed pipeline name values and prevented empty string names.
1. verify special characters can now be used in pipeline names
2. verify that special characters do not break pipeline urls
3. verify that pipeline editing cans till be accessed via the pipeline list, inspetc button & clone button

Loosen restrictions on Pipeline Naming
